import argparse
import json
import logging
import os
import re
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import fitz  # PyMuPDF
import ollama
import requests
import soundfile as sf
from kokoro_onnx import Kokoro
from moviepy import (
    AudioFileClip,
    ColorClip,
    VideoFileClip,
    concatenate_videoclips,
)
from dotenv import load_dotenv

# Load environment variables from a .env file if present (optional)
load_dotenv()

# ---------------------------------------------------------------------------
# Configuration and logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(message)s",
)
log = logging.getLogger("freevi")

# Target resolution for the output video
TARGET_WIDTH = 1920
TARGET_HEIGHT = 1080
TARGET_FPS = 24
TARGET_PRESET = "medium"  # x264 encoding preset

# Directory where Kokoro models are stored (relative to this script)
_env_kokoro = os.environ.get("KOKORO_MODEL_DIR", "")
if _env_kokoro:
    KOKORO_MODEL_DIR = Path(_env_kokoro)
else:
    KOKORO_MODEL_DIR = Path(__file__).parent / "kokoro-v1.0"

KOKORO_ONNX_PATH = KOKORO_MODEL_DIR / "kokoro-v1.0.onnx"
KOKORO_VOICES_PATH = KOKORO_MODEL_DIR / "voices-v1.0.bin"


# ---------------------------------------------------------------------------
# Kokoro 1.0 language and voice registry
# ---------------------------------------------------------------------------
# Each key is a Kokoro lang_code (single char), mapped to metadata and voices.
# The espeak_code is passed to misaki EspeakG2P (or None for non-espeak G2P).
# Voices are ordered: females first, then males, alphabetically.

KOKORO_LANGUAGES: dict[str, dict] = {
    "a": {
        "label": "English (American)",
        "espeak_code": "en-us",
        "voices": [
            "af_alloy", "af_aoede", "af_bella", "af_heart", "af_jessica",
            "af_kore", "af_nicole", "af_nova", "af_river", "af_sarah", "af_sky",
            "am_adam", "am_echo", "am_eric", "am_fenrir", "am_liam",
            "am_michael", "am_onyx", "am_puck", "am_santa",
        ],
    },
    "b": {
        "label": "English (British)",
        "espeak_code": "en-gb",
        "voices": [
            "bf_alice", "bf_emma", "bf_isabella", "bf_lily",
            "bm_daniel", "bm_fable", "bm_george", "bm_lewis",
        ],
    },
    "e": {
        "label": "Spanish",
        "espeak_code": "es",
        "voices": ["ef_dora", "em_alex", "em_santa"],
    },
    "f": {
        "label": "French",
        "espeak_code": "fr-fr",
        "voices": ["ff_siwis"],
    },
    "h": {
        "label": "Hindi",
        "espeak_code": "hi",
        "voices": ["hf_alpha", "hf_beta", "hm_omega", "hm_psi"],
    },
    "i": {
        "label": "Italian",
        "espeak_code": "it",
        "voices": ["if_sara", "im_nicola"],
    },
    "j": {
        "label": "Japanese",
        "espeak_code": None,  # uses misaki[ja], not espeak
        "voices": [
            "jf_alpha", "jf_gongitsune", "jf_nezumi", "jf_tebukuro",
            "jm_kumo",
        ],
    },
    "p": {
        "label": "Portuguese (Brazilian)",
        "espeak_code": "pt-br",
        "voices": ["pf_dora", "pm_alex", "pm_santa"],
    },
    "z": {
        "label": "Chinese (Mandarin)",
        "espeak_code": None,  # uses misaki[zh], not espeak
        "voices": [
            "zf_xiaobei", "zf_xiaoni", "zf_xiaoxiao", "zf_xiaoyi",
            "zm_yunjian", "zm_yunxi", "zm_yunxia", "zm_yunyang",
        ],
    },
}

# Reverse lookup: voice_id → lang_code
_VOICE_TO_LANG: dict[str, str] = {}
for _lc, _info in KOKORO_LANGUAGES.items():
    for _v in _info["voices"]:
        _VOICE_TO_LANG[_v] = _lc


def get_lang_code_for_voice(voice: str) -> str:
    """Returns the Kokoro lang_code ('a', 'e', 'i', ...) for a given voice ID."""
    return _VOICE_TO_LANG.get(voice, voice[0] if voice else "a")


def get_voices_for_lang(lang_code: str) -> list[str]:
    """Returns the list of voice IDs available for a given lang_code."""
    info = KOKORO_LANGUAGES.get(lang_code)
    return list(info["voices"]) if info else []


def get_language_label(lang_code: str) -> str:
    """Returns the human-readable label for a Kokoro lang_code."""
    info = KOKORO_LANGUAGES.get(lang_code)
    return info["label"] if info else lang_code


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------
@dataclass
class Scene:
    """Represents a single scene in the video."""

    number: int
    narrator_text: str
    video_query: str
    audio_path: str = ""
    audio_duration: float = 0.0
    video_path: str = ""
    processed_video_path: str = ""


@dataclass
class Script:
    """Contains all scenes generated by the LLM."""

    scenes: list[Scene] = field(default_factory=list)


# ---------------------------------------------------------------------------
# 1. PDF READING MODULE (PyMuPDF)
# ---------------------------------------------------------------------------
def extract_pdf_text(pdf_path: str) -> str:
    """
    Extracts all text from a PDF file using PyMuPDF.

    Args:
        pdf_path: Path to the PDF file.

    Returns:
        Full text extracted from the PDF.

    Raises:
        FileNotFoundError: If the file does not exist.
        RuntimeError: If the PDF cannot be read.
    """
    path = Path(pdf_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {pdf_path}")

    try:
        doc = fitz.open(str(path))
        pages_text = []
        total_pages = len(doc)
        for page_num, page in enumerate(doc, start=1):
            text = page.get_text("text")
            if text.strip():
                pages_text.append(text.strip())
                log.info(f"  Page {page_num}: {len(text)} characters extracted")
        doc.close()

        result = "\n\n".join(pages_text)
        if not result.strip():
            raise RuntimeError("The PDF contains no extractable text.")

        log.info(f"  Total: {len(result)} characters from {total_pages} pages")
        return result

    except Exception as e:
        raise RuntimeError(f"Error reading PDF: {e}")


# ---------------------------------------------------------------------------
# 2. SCRIPT GENERATION MODULE (Ollama - Local LLM)
# ---------------------------------------------------------------------------

# The part the user can freely customise in the GUI.
# It is injected between the role description and the strict JSON rules,
# so even if the user clears it completely the pipeline keeps working.
DEFAULT_CUSTOM_INSTRUCTIONS = """\
- Keep the narration natural and conversational (40-80 words per scene).
- Avoid excessive technical jargon. Imagine speaking to a general audience.\
"""

# Fixed parts that must always be present for the pipeline to work.
# {max_scenes} and {narration_language} are replaced at runtime.
# {{ / }} are literal braces in the JSON example.
_SYSTEM_PROMPT_HEAD = """\
You are an expert scriptwriter for educational and informational videos.
Your task is to convert an academic/informational text into a narrated video script.

MANDATORY LANGUAGE RULE (NON-NEGOTIABLE):
- ALL narrator_text MUST be written in **{narration_language}**.
- This is an absolute requirement. Do NOT write narrator_text in any other language.
- Even if the source text is in a different language, translate and narrate in {narration_language}.

STRICT RULES:
- Generate between 4 and {max_scenes} scenes (adjust based on text length).
- Each scene must be self-contained and flow naturally into the next.
- "narrator_text": The narration text for this scene (MUST be in {narration_language}).
- "video_query": 2 to 5 words in ENGLISH to search for a stock video clip.
  CRITICAL: The query MUST visually represent the specific subject of THAT scene's
  narrator_text, not the document topic in general.
  Ask yourself: "What does a camera show while the narrator says this sentence?"
  Rules for the query:
    * Be concrete and visual — name objects, actions, or settings that can be filmed.
    * Match the scene content — if the narrator discusses data analysis, write
      "data analyst working computer", not "technology".
    * Use 3-5 words for specificity; single generic words produce unrelated footage.
    * Write in English regardless of the narration language.
  Good examples:  "scientists analyzing dna samples", "city traffic aerial view",
                  "students working laptops classroom", "factory assembly line robots"
  Bad examples:   "technology", "science", "research", "nature landscape"\
"""

_SYSTEM_PROMPT_TAIL = """\

RESPOND ONLY with valid JSON in this exact structure:
{{
  "scenes": [
    {{
      "narrator_text": "narration text in {narration_language}...",
      "video_query": "english query"
    }}
  ]
}}\
"""

# Legacy alias kept so any code that imports SYSTEM_PROMPT_TPL still works.
SYSTEM_PROMPT_TPL = _SYSTEM_PROMPT_HEAD + "\n{custom_instructions}\n" + _SYSTEM_PROMPT_TAIL


def build_system_prompt(
    max_scenes: int,
    custom_instructions: str = "",
    narration_language: str = "Spanish",
) -> str:
    """
    Assembles the final system prompt from the fixed parts and the
    user-supplied custom instructions.

    The custom instructions are sandwiched between the role/rules header and
    the mandatory JSON format block, so:
      - An empty string is perfectly valid (the pipeline still works).
      - The user cannot accidentally remove the JSON format requirement.
      - The user can change tone, length, etc. freely.
      - The narration language is enforced in the fixed parts and cannot be
        overridden by the user's custom instructions.

    Args:
        max_scenes: Maximum number of scenes to request from the LLM.
        custom_instructions: Free-form text from the GUI prompt editor.
                             Defaults to DEFAULT_CUSTOM_INSTRUCTIONS.
        narration_language: The language name in English (e.g. "Spanish",
                           "English (American)") injected into the prompt
                           so the LLM is forced to narrate in it.

    Returns:
        The complete system prompt string ready to send to Ollama.
    """
    instructions = custom_instructions.strip() or DEFAULT_CUSTOM_INSTRUCTIONS
    head = _SYSTEM_PROMPT_HEAD.format(
        max_scenes=max_scenes,
        narration_language=narration_language,
    )
    tail = _SYSTEM_PROMPT_TAIL.format(narration_language=narration_language)
    return f"{head}\n\n{instructions}\n{tail}"


def _clean_json(text: str) -> str:
    """
    Attempts to extract valid JSON from an LLM response that may include:
    - Markdown code fences (```json ... ```)
    - Preamble text before the JSON
    - Extra text after the JSON
    - Typographic quotes or other minor artifacts

    Returns:
        The most likely JSON string, ready for json.loads().
    """
    # 1. Strip markdown code fences: ```json ... ``` or ``` ... ```
    match = re.search(r"```(?:json)?\s*([\s\S]*?)```", text, re.IGNORECASE)
    if match:
        text = match.group(1).strip()

    # 2. Extract the first balanced JSON object {...}
    start = text.find("{")
    if start == -1:
        return text  # Cannot clean further; let json.loads fail with a clear message

    # Find the matching closing brace
    depth = 0
    for i, c in enumerate(text[start:], start=start):
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]

    # No balanced closing brace found; return from { to end
    return text[start:]


def generate_script(
    pdf_text: str,
    model: str = "qwen3",
    max_scenes: int = 8,
    custom_instructions: str = "",
    context_size: int = 8192,
    narration_language: str = "Spanish",
) -> Script:
    """
    Sends the PDF text to a local LLM via Ollama to generate the video script.

    Uses format='json' to enforce structured JSON output.

    Token budget strategy
    ---------------------
    Each scene in the JSON response costs roughly 200-300 tokens (narrator text
    ~150-200 tokens + video_query + JSON overhead).  We reserve
    ``num_predict = max_scenes * 300 + 256`` tokens for the output, then give
    the remaining ``context_size - num_predict`` tokens to the input (system
    prompt + PDF text).  The PDF text is truncated so the total fits.

    If the response is still truncated (invalid JSON), the function retries
    up to twice: first with ``max_scenes`` halved, then with ``max_scenes=2``
    as a last resort.

    Args:
        pdf_text: Text extracted from the PDF.
        model: Name of the Ollama model to use.
        max_scenes: Maximum number of scenes to generate.
        custom_instructions: Optional free-form instructions injected into the
            system prompt (tone, length, etc.). If empty, the
            DEFAULT_CUSTOM_INSTRUCTIONS are used as fallback.
        context_size: Ollama num_ctx option — the model's context window in
            tokens. Increase this if the PDF text is long. Default: 8192.
        narration_language: Human-readable language name (e.g. "Spanish",
            "English (American)") forced into the system prompt so the LLM
            writes all narrator_text in that language.

    Returns:
        Script with the list of scenes.

    Raises:
        ConnectionError: If Ollama is not available.
        ValueError: If the response does not have the expected format.
    """
    return _generate_script_attempt(
        pdf_text, model, max_scenes, custom_instructions, context_size,
        narration_language, attempt=1,
    )


def _generate_script_attempt(
    pdf_text: str,
    model: str,
    max_scenes: int,
    custom_instructions: str,
    context_size: int,
    narration_language: str,
    attempt: int,
) -> Script:
    """
    Single attempt at script generation. Called by generate_script(); retried
    with a smaller max_scenes if the JSON response is truncated.
    """
    # ── Token budget ──────────────────────────────────────────────────────────
    # Reserve output tokens: ~300 tokens per scene + 256 for JSON scaffolding.
    # 300 tokens/scene is conservative enough to handle verbose models (e.g.
    # gemma3) whose narrator_text easily exceeds 200 tokens per scene.
    num_predict = max_scenes * 300 + 256

    # Thinking models (e.g. lfm2.5-thinking, qwq, deepseek-r1) spend a large
    # portion of num_predict on an internal <think>…</think> chain before
    # writing the actual JSON.  We add a fixed overhead so there are enough
    # tokens left for the real output after thinking finishes.
    _THINKING_KEYWORDS = ("thinking", "think", "qwq", "r1", "reasoner")
    _is_thinking_model = any(kw in model.lower() for kw in _THINKING_KEYWORDS)
    if _is_thinking_model:
        _THINKING_OVERHEAD = 2048  # tokens consumed by internal reasoning
        num_predict += _THINKING_OVERHEAD
        log.info(
            f"  Thinking model detected ('{model}'). "
            f"Adding {_THINKING_OVERHEAD} token overhead for reasoning "
            f"(total num_predict={num_predict})."
        )

    # Tokens available for input (system prompt + user text).
    # System prompt + wrappers ≈ 400 tokens; give the rest to the PDF text.
    input_token_budget = context_size - num_predict - 400
    # 1 token ≈ 3 characters (conservative estimate for mixed-language text).
    max_chars = max(500, input_token_budget * 3)

    if len(pdf_text) > max_chars:
        pdf_text = pdf_text[:max_chars] + "\n\n[... text truncated due to length ...]"
        log.warning(f"  Text truncated to {max_chars} characters for the model.")

    system_prompt = build_system_prompt(
        max_scenes, custom_instructions, narration_language,
    )
    user_prompt = (
        f"Convert the following text into a narrated video script:\n\n"
        f"---START OF TEXT---\n{pdf_text}\n---END OF TEXT---"
    )

    log.info(
        f"  Context window: {context_size} tokens (num_ctx), "
        f"output reserved: {num_predict} tokens (num_predict), "
        f"max scenes: {max_scenes}"
    )

    try:
        response = ollama.chat(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            format="json",
            options={"num_ctx": context_size, "num_predict": num_predict},
        )
    except Exception as e:
        raise ConnectionError(
            f"Error connecting to Ollama. Is the server running?\n"
            f"Run: ollama serve\n"
            f"Details: {e}"
        )

    # Parse JSON response
    content = response["message"]["content"]

    # Thinking models (e.g. lfm2.5-thinking) may produce an empty content field
    # if the reasoning chain consumed all num_predict tokens.  As a last resort,
    # scan the thinking text for a JSON block — the model sometimes embeds the
    # final answer there before running out of space.
    if not content.strip():
        thinking = response["message"].get("thinking", "") or ""
        if thinking:
            log.warning(
                "  content is empty; scanning thinking field for embedded JSON..."
            )
            # Extract the last {...} block from the thinking text.
            _json_blocks = re.findall(r'\{[\s\S]*\}', thinking)
            if _json_blocks:
                content = _json_blocks[-1]
                log.info(f"  Found JSON in thinking field ({len(content)} characters).")

    log.info(f"  LLM response received ({len(content)} characters)")

    # Check for Ollama stop reason — if the model stopped due to length the
    # JSON is certainly truncated; retry immediately without even trying to parse.
    stop_reason = (
        response.get("done_reason", "")
        or response.get("stop_reason", "")
    )
    if stop_reason == "length" and attempt < 3:
        reduced = max(2, max_scenes // 2) if attempt == 1 else 2
        log.warning(
            f"  Response cut off by token limit (done_reason=length). "
            f"Retrying with max_scenes={reduced} (attempt {attempt + 1}/3)..."
        )
        return _generate_script_attempt(
            pdf_text, model, reduced, custom_instructions, context_size,
            narration_language, attempt=attempt + 1,
        )

    cleaned = _clean_json(content)
    log.debug(f"  JSON after cleaning: {cleaned[:300]}")

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        # Try replacing typographic quotes first
        cleaned2 = (
            cleaned
            .replace("\u201c", '"').replace("\u201d", '"')
            .replace("\u2018", "'").replace("\u2019", "'")
        )
        try:
            data = json.loads(cleaned2)
        except json.JSONDecodeError:
            # If this is the first attempt, the truncation may not have been
            # caught by done_reason — retry with fewer scenes before giving up.
            if attempt < 3:
                reduced = max(2, max_scenes // 2) if attempt == 1 else 2
                log.warning(
                    f"  JSON invalid (likely truncated). "
                    f"Retrying with max_scenes={reduced} (attempt {attempt + 1}/3)..."
                )
                return _generate_script_attempt(
                    pdf_text, model, reduced, custom_instructions,
                    context_size, narration_language, attempt=attempt + 1,
                )
            raise ValueError(
                f"The LLM did not return valid JSON even after attempting to clean "
                f"the response.\n"
                f"First 500 characters received:\n{content[:500]}\n"
                f"JSON error: {e}"
            )

    # Validate structure — tolerate key name variations from small models
    scenes_list = None
    for key in ("scenes", "escenas", "script", "guion", "video_scenes", "scene"):
        val = data.get(key)
        if isinstance(val, list) and val:
            scenes_list = val
            break
    # If the JSON is directly a list instead of an object
    if scenes_list is None and isinstance(data, list):
        scenes_list = data
    if scenes_list is None:
        raise ValueError(
            f"The JSON does not contain a recognizable list of scenes.\n"
            f"Keys received: {list(data.keys()) if isinstance(data, dict) else type(data)}"
        )

    script = Script()
    for i, raw_scene in enumerate(scenes_list, start=1):
        if not isinstance(raw_scene, dict):
            log.warning(f"  Scene {i}: unexpected element ({type(raw_scene)}), skipping.")
            continue
        # Tolerate field name variations from different models
        narrator_text = (
            raw_scene.get("narrator_text")
            or raw_scene.get("texto_narrador")
            or raw_scene.get("narrator")
            or raw_scene.get("narrador")
            or raw_scene.get("text")
            or ""
        ).strip()
        video_query = (
            raw_scene.get("video_query")
            or raw_scene.get("query")
            or raw_scene.get("visual")
            or raw_scene.get("video")
            or ""
        ).strip()

        if not narrator_text:
            log.warning(f"  Scene {i}: no narrator text, skipping.")
            continue
        if not video_query:
            video_query = "nature landscape"  # Generic fallback
            log.warning(f"  Scene {i}: no video_query, using fallback '{video_query}'")

        # Limit query to 5 words maximum
        video_query = " ".join(video_query.split()[:5])

        script.scenes.append(
            Scene(number=i, narrator_text=narrator_text, video_query=video_query)
        )

    if not script.scenes:
        raise ValueError("The LLM did not generate any valid scenes.")

    log.info(f"  Script generated: {len(script.scenes)} scenes")
    return script


# ---------------------------------------------------------------------------
# 3. AUDIO MODULE (Kokoro 1.0 via kokoro-onnx)
# ---------------------------------------------------------------------------
class AudioEngine:
    """
    Generates TTS audio using Kokoro 1.0 with ONNX Runtime.

    Supports all Kokoro languages.  For espeak-backed languages (American
    English, British English, Spanish, French, Hindi, Italian, Portuguese)
    it uses ``misaki.espeak.EspeakG2P`` for phonemization.  For Japanese
    and Mandarin Chinese it falls back to Kokoro's built-in G2P.
    """

    def __init__(
        self,
        voice: str = "af_heart",
        speed: float = 1.0,
        lang_code: str = "",
    ):
        """
        Initializes the audio engine.

        Args:
            voice: Kokoro voice ID (e.g. ``af_heart``, ``em_alex``).
            speed: Speech speed (1.0 = normal).
            lang_code: Kokoro single-char language code (``a``, ``e``, …).
                       If empty, inferred from the voice prefix.
        """
        self.voice = voice
        self.speed = speed
        self.lang_code = lang_code or get_lang_code_for_voice(voice)
        self.kokoro = None
        self.g2p = None

    def _initialize(self):
        """Loads the Kokoro model and the appropriate G2P module (lazy)."""
        if self.kokoro is not None:
            return

        # Verify model files exist
        if not KOKORO_ONNX_PATH.exists():
            raise FileNotFoundError(
                f"Kokoro model not found at: {KOKORO_ONNX_PATH}\n"
                f"Download it from: https://github.com/thewh1teagle/kokoro-onnx/releases"
            )
        if not KOKORO_VOICES_PATH.exists():
            raise FileNotFoundError(
                f"Kokoro voices not found at: {KOKORO_VOICES_PATH}\n"
                f"Download them from: https://github.com/thewh1teagle/kokoro-onnx/releases"
            )

        log.info("  Loading Kokoro v1.0 model (this may take a few seconds)...")
        self.kokoro = Kokoro(str(KOKORO_ONNX_PATH), str(KOKORO_VOICES_PATH))

        # Initialize G2P based on language
        lang_info = KOKORO_LANGUAGES.get(self.lang_code, {})
        espeak_code = lang_info.get("espeak_code")
        lang_label = lang_info.get("label", self.lang_code)

        if espeak_code is not None:
            # espeak-backed language — use misaki EspeakG2P
            try:
                from misaki.espeak import EspeakG2P
                self.g2p = EspeakG2P(language=espeak_code)
                log.info(f"  G2P initialized for {lang_label} (espeak: {espeak_code})")
            except ImportError:
                log.warning(
                    f"  misaki not available. Using direct mode for {lang_label}.\n"
                    f"  For better quality: pip install misaki"
                )
                self.g2p = None
        else:
            # Japanese / Chinese — Kokoro handles G2P internally
            log.info(f"  {lang_label}: using Kokoro built-in G2P (no espeak needed)")
            self.g2p = None

    def generate_audio(self, text: str, output_path: str) -> float:
        """
        Generates a .wav file from text in the configured language.

        Args:
            text: Text to synthesize (in the voice's language).
            output_path: Path where the .wav file will be saved.

        Returns:
            Exact audio duration in seconds.
        """
        self._initialize()

        try:
            if self.g2p is not None:
                # Convert text to phonemes via misaki espeak
                # misaki 0.7+ EspeakG2P returns str directly
                phonemes = self.g2p(text)
                if not phonemes:
                    log.warning("  G2P returned empty phonemes, using text directly.")
                    phonemes = text
                samples, sample_rate = self.kokoro.create(
                    phonemes,
                    voice=self.voice,
                    speed=self.speed,
                    is_phonemes=True,
                )
            else:
                # Direct mode: Japanese, Chinese, or fallback when misaki
                # is not installed. Pass lang_code so Kokoro picks the
                # correct internal G2P.
                samples, sample_rate = self.kokoro.create(
                    text,
                    voice=self.voice,
                    speed=self.speed,
                    lang=self.lang_code,
                )

            # Save audio
            sf.write(output_path, samples, sample_rate)

            # Calculate exact duration from samples
            duration = len(samples) / sample_rate
            log.info(
                f"  Audio generated: {duration:.2f}s "
                f"({len(samples)} samples @ {sample_rate}Hz)"
            )
            return duration

        except Exception as e:
            raise RuntimeError(f"Error generating audio with Kokoro: {e}")


# ---------------------------------------------------------------------------
# 4. VISUAL MODULE (Pexels API - 100% Free)
# ---------------------------------------------------------------------------
PEXELS_API_URL = "https://api.pexels.com/videos/search"


def get_pexels_api_key() -> str:
    """
    Retrieves the Pexels API key from environment variable.

    Returns:
        The API key.

    Raises:
        EnvironmentError: If the variable is not set.
    """
    api_key = os.environ.get("PEXELS_API_KEY", "")
    if not api_key:
        raise EnvironmentError(
            "PEXELS_API_KEY environment variable is not set.\n"
            "Get a free key at: https://www.pexels.com/api/\n"
            "Set it with: export PEXELS_API_KEY='your_key_here'"
        )
    return api_key


def search_pexels_video(
    query: str,
    api_key: str,
    orientation: str = "landscape",
    target_duration: float = 0.0,
) -> dict | None:
    """
    Searches for a video on Pexels and returns info about the best result.

    Fetches up to 15 candidates and selects the one whose duration is closest
    to *target_duration* (the audio length). This avoids always picking the
    first (most popular) result, which is often only loosely related to the
    query despite having a matching tag.

    Args:
        query: Search terms in English (2-5 words).
        api_key: Pexels API key.
        orientation: "landscape", "portrait" or "square".
        target_duration: Preferred video duration in seconds (0 = pick longest).

    Returns:
        Dict with 'url' (download link), 'width', 'height', 'duration' or None.
    """
    headers = {"Authorization": api_key}
    params = {
        "query": query,
        "per_page": 15,
        "orientation": orientation,
        "size": "medium",
    }

    try:
        resp = requests.get(PEXELS_API_URL, headers=headers, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except requests.exceptions.RequestException as e:
        log.error(f"  Pexels API error: {e}")
        return None

    videos = data.get("videos", [])
    if not videos:
        log.warning(f"  No videos found for '{query}'")
        return None

    # Collect all valid candidates (video + best file) from the full result set
    candidates = []
    for video in videos:
        files = video.get("video_files", [])
        best_file = None

        # Prefer the smallest resolution that is still >= 720p HD
        for f in files:
            if f.get("file_type") != "video/mp4":
                continue
            w = f.get("width", 0)
            h = f.get("height", 0)
            if w >= 1280 and h >= 720:
                if best_file is None or w < best_file.get("width", 9999):
                    best_file = f

        # Fallback: any mp4 if no HD found
        if best_file is None:
            for f in files:
                if f.get("file_type") == "video/mp4":
                    best_file = f
                    break

        if best_file:
            candidates.append({
                "url": best_file["link"],
                "width": best_file.get("width", 0),
                "height": best_file.get("height", 0),
                "duration": video.get("duration", 0),
            })

    if not candidates:
        log.warning(f"  No mp4 files found for '{query}'")
        return None

    # Select the candidate whose duration is closest to the target audio length.
    # If target_duration is 0 (unknown), pick the longest video (more material
    # for looping and less likely to loop with a visible cut).
    if target_duration > 0:
        best = min(candidates, key=lambda c: abs(c["duration"] - target_duration))
    else:
        best = max(candidates, key=lambda c: c["duration"])

    log.info(
        f"  Pexels: {len(candidates)} candidates for '{query}' → "
        f"selected {best['duration']}s video "
        f"(target {target_duration:.1f}s)"
    )
    return best


def download_video(url: str, output_path: str) -> bool:
    """
    Downloads a video from a URL.

    Args:
        url: Direct URL of the video file.
        output_path: Local path where the file will be saved.

    Returns:
        True if the download was successful.
    """
    try:
        log.info(f"  Downloading video...")
        resp = requests.get(url, stream=True, timeout=60)
        resp.raise_for_status()

        total_size = int(resp.headers.get("content-length", 0))
        downloaded = 0

        with open(output_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=1024 * 1024):  # 1MB chunks
                f.write(chunk)
                downloaded += len(chunk)

        size_mb = downloaded / (1024 * 1024)
        log.info(f"  Downloaded: {size_mb:.1f} MB → {output_path}")
        return True

    except requests.exceptions.RequestException as e:
        log.error(f"  Error downloading video: {e}")
        return False


def search_and_download_video(
    query: str,
    api_key: str,
    output_path: str,
    orientation: str = "landscape",
    target_duration: float = 0.0,
) -> bool:
    """
    Searches and downloads a video from Pexels.

    Fallback strategy (in order):
      1. Full query (e.g. "scientists analyzing dna samples")
      2. First two words of the query (e.g. "scientists analyzing")
      3. First word of the query (e.g. "scientists")
      4. Generic domain-neutral fallbacks: "people working", "abstract motion",
         "urban timelapse"

    Args:
        query: Original search terms (2-5 words from the LLM).
        api_key: Pexels API key.
        output_path: Path where the video will be saved.
        orientation: "landscape", "portrait" or "square".
        target_duration: Audio duration in seconds — used to pick the best
            Pexels result (closest duration = less looping).

    Returns:
        True if downloaded successfully.
    """
    words = query.split()

    # Build the fallback chain: progressively shorter versions of the original
    # query, then generic fallbacks as last resort.
    attempts: list[str] = [query]
    if len(words) > 2:
        attempts.append(" ".join(words[:2]))   # first two words
    if len(words) > 1:
        attempts.append(words[0])              # first word only
    attempts += ["people working", "abstract motion", "urban timelapse"]

    # Remove duplicates while preserving order
    seen: set[str] = set()
    unique_attempts: list[str] = []
    for a in attempts:
        if a not in seen:
            seen.add(a)
            unique_attempts.append(a)

    info = None
    for attempt in unique_attempts:
        log.info(f"  Searching Pexels: '{attempt}'")
        info = search_pexels_video(attempt, api_key, orientation, target_duration)
        if info is not None:
            if attempt != query:
                log.warning(f"  Original query '{query}' failed — using fallback '{attempt}'")
            break

    if info is None:
        log.error(f"  Could not find any video (query: '{query}')")
        return False

    return download_video(info["url"], output_path)


# ---------------------------------------------------------------------------
# 5. ASSEMBLY MODULE (MoviePy)
# ---------------------------------------------------------------------------
def assemble_scene_from_raw(
    raw_video_path: str,
    audio_path: str,
    target_duration: float,
    output_path: str,
) -> str:
    """
    Trims/loops the raw stock video to the exact audio duration, resizes it,
    and mixes in the audio — all in a **single encode pass**.

    This replaces the previous two-step approach (fit_video_to_duration →
    assemble_scene) which wrote an intermediate _processed.mp4 and then
    re-encoded it a second time.  Doing it in one pass halves the CPU time
    per scene.

    Args:
        raw_video_path: Path to the video downloaded from Pexels.
        audio_path: Path to the .wav audio file for this scene.
        target_duration: Exact audio duration in seconds.
        output_path: Path for the finished scene video file (video + audio).

    Returns:
        Path to the assembled scene video (same as output_path).
    """
    clip = VideoFileClip(raw_video_path)
    audio = AudioFileClip(audio_path)

    log.info(
        f"  Original video: {clip.duration:.2f}s → Target: {target_duration:.2f}s"
    )

    # Trim or loop to match audio duration exactly
    if clip.duration >= target_duration:
        adjusted = clip.subclipped(0, target_duration)
    else:
        repetitions = int(target_duration / clip.duration) + 1
        adjusted = concatenate_videoclips([clip] * repetitions, method="compose")
        adjusted = adjusted.subclipped(0, target_duration)

    # Resize to target resolution if needed
    w, h = adjusted.size
    if w != TARGET_WIDTH or h != TARGET_HEIGHT:
        adjusted = adjusted.resized(new_size=(TARGET_WIDTH, TARGET_HEIGHT))

    # Set FPS and attach audio — single encode pass
    adjusted = adjusted.with_fps(TARGET_FPS).with_audio(audio)

    adjusted.write_videofile(
        output_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )

    clip.close()
    audio.close()
    adjusted.close()

    log.info(f"  Scene assembled: {output_path}")
    return output_path


def fit_video_to_duration(video_path: str, target_duration: float, output_path: str) -> str:
    """
    Adjusts a stock video to match the exact audio duration.

    .. deprecated::
        Use :func:`assemble_scene_from_raw` instead, which combines this step
        with audio mixing into a single encode pass.

    If the video is longer → trim it (subclip).
    If the video is shorter → loop it until it covers the duration.

    Also resizes to TARGET_WIDTH x TARGET_HEIGHT if needed.

    Args:
        video_path: Path to the video downloaded from Pexels.
        target_duration: Exact duration in seconds (from audio).
        output_path: Path where the processed video will be saved.

    Returns:
        Path to the processed video.
    """
    clip = VideoFileClip(video_path)
    video_duration = clip.duration

    log.info(
        f"  Original video: {video_duration:.2f}s → "
        f"Target: {target_duration:.2f}s"
    )

    if video_duration >= target_duration:
        # Video is longer: trim it
        adjusted = clip.subclipped(0, target_duration)
    else:
        # Video is shorter: loop it
        repetitions = int(target_duration / video_duration) + 1
        adjusted = concatenate_videoclips([clip] * repetitions, method="compose")
        adjusted = adjusted.subclipped(0, target_duration)

    # Resize to target resolution if needed
    w, h = adjusted.size
    if w != TARGET_WIDTH or h != TARGET_HEIGHT:
        adjusted = adjusted.resized(new_size=(TARGET_WIDTH, TARGET_HEIGHT))

    # Set target FPS
    adjusted = adjusted.with_fps(TARGET_FPS)

    adjusted.write_videofile(
        output_path,
        codec="libx264",
        audio=False,  # Audio is added later
        preset=TARGET_PRESET,
        logger=None,  # Suppress ffmpeg output
    )

    clip.close()
    adjusted.close()

    log.info(f"  Adjusted video saved: {output_path}")
    return output_path


def assemble_scene(scene: Scene, output_path: str) -> str:
    """
    Combines the processed video with the audio for a scene.

    Args:
        scene: Scene with audio and processed video paths.
        output_path: Path for the final scene video file.

    Returns:
        Path to the assembled video.
    """
    video = VideoFileClip(scene.processed_video_path)
    audio = AudioFileClip(scene.audio_path)

    video_with_audio = video.with_audio(audio)

    video_with_audio.write_videofile(
        output_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )

    video.close()
    audio.close()
    video_with_audio.close()

    log.info(f"  Scene assembled: {output_path}")
    return output_path


def concatenate_scenes(scene_paths: list[str], final_path: str) -> str:
    """
    Concatenates all scene files into a single final video **without
    re-encoding** using the ffmpeg ``concat`` demuxer.

    All scene files must share the same codec, resolution and frame-rate —
    which is guaranteed by :func:`assemble_scene_from_raw` (libx264 + aac,
    TARGET_WIDTH × TARGET_HEIGHT, TARGET_FPS).  Under these conditions ffmpeg
    simply copies the compressed packets straight into the output container in
    a fraction of the time that a full transcode would take.

    Falls back to the MoviePy re-encode path if ffmpeg is not available or
    the stream-copy fails for any reason.

    Args:
        scene_paths: Ordered list of paths to each assembled scene .mp4 file.
        final_path: Output path for the final concatenated video.

    Returns:
        Path to the final video (same as *final_path*).
    """
    import shutil
    import subprocess

    # ── Build a temporary concat list file ───────────────────────────────────
    # ffmpeg concat demuxer format:
    #   file '/absolute/path/to/scene.mp4'
    #   file '/absolute/path/to/scene2.mp4'
    #   ...
    list_fd, list_path = tempfile.mkstemp(suffix=".txt", prefix="freevi_concat_")
    try:
        with os.fdopen(list_fd, "w", encoding="utf-8") as f:
            for p in scene_paths:
                # Use absolute paths and escape single quotes
                abs_p = os.path.abspath(p).replace("'", "'\\''")
                f.write(f"file '{abs_p}'\n")

        cmd = [
            "ffmpeg", "-y",
            "-f", "concat",
            "-safe", "0",
            "-i", list_path,
            "-c", "copy",          # stream copy — no re-encode
            final_path,
        ]
        log.info(f"  ffmpeg concat (stream copy): {len(scene_paths)} scenes → {final_path}")
        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        if result.returncode != 0:
            err = result.stderr.decode(errors="replace")
            raise RuntimeError(f"ffmpeg concat failed:\n{err}")

    except FileNotFoundError:
        # ffmpeg binary not on PATH — fall back to MoviePy
        log.warning("  ffmpeg not found on PATH; falling back to MoviePy re-encode.")
        os.unlink(list_path)
        return _concatenate_scenes_moviepy(scene_paths, final_path)
    except Exception as e:
        log.warning(f"  ffmpeg concat failed ({e}); falling back to MoviePy re-encode.")
        return _concatenate_scenes_moviepy(scene_paths, final_path)
    finally:
        if os.path.exists(list_path):
            os.unlink(list_path)

    log.info(f"Final video generated: {final_path}")
    return final_path


def _concatenate_scenes_moviepy(scene_paths: list[str], final_path: str) -> str:
    """
    Fallback concatenation via MoviePy (full re-encode).
    Used only when the ffmpeg stream-copy path is unavailable.
    """
    clips = [VideoFileClip(path) for path in scene_paths]
    final_video = concatenate_videoclips(clips, method="compose")
    final_video.write_videofile(
        final_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )
    for clip in clips:
        clip.close()
    final_video.close()
    log.info(f"Final video generated (MoviePy fallback): {final_path}")
    return final_path


# ---------------------------------------------------------------------------
# 6. MAIN ORCHESTRATOR
# ---------------------------------------------------------------------------
class VideoGenerator:
    """
    Orchestrates the entire video generation pipeline.

    Per-scene pipeline (strict order for synchronization):
      1. LLM generates narrator text + visual query
      2. Kokoro generates audio → exact duration is measured
      3. Pexels downloads video → trimmed/looped to that duration
      4. MoviePy combines audio + video
      5. All scenes are concatenated at the end
    """

    def __init__(
        self,
        pdf_path: str,
        llm_model: str = "qwen3",
        voice: str = "af_heart",
        voice_speed: float = 1.0,
        output_path: str = "output/video_final.mp4",
        max_scenes: int = 8,
        context_size: int = 8192,
        lang_code: str = "a",
    ):
        self.pdf_path = pdf_path
        self.llm_model = llm_model
        self.output_path = output_path
        self.max_scenes = max_scenes
        self.context_size = context_size
        self.lang_code = lang_code
        self.audio_engine = AudioEngine(
            voice=voice, speed=voice_speed, lang_code=lang_code,
        )
        self.pexels_api_key = get_pexels_api_key()
        self.temp_dir = tempfile.mkdtemp(prefix="freevi_")
        log.info(f"Temporary directory: {self.temp_dir}")

    def run(self):
        """Runs the full pipeline."""
        # ── Step 1: Extract PDF text ──
        log.info("=" * 60)
        log.info("STEP 1/5: Extracting text from PDF...")
        log.info("=" * 60)
        pdf_text = extract_pdf_text(self.pdf_path)

        # ── Step 2: Generate script with LLM ──
        log.info("=" * 60)
        log.info(f"STEP 2/5: Generating script with {self.llm_model}...")
        log.info("=" * 60)
        narration_lang = get_language_label(self.lang_code)
        script = generate_script(
            pdf_text,
            self.llm_model,
            max_scenes=self.max_scenes,
            context_size=self.context_size,
            narration_language=narration_lang,
        )

        # Show script summary
        for scene in script.scenes:
            log.info(
                f"  Scene {scene.number}: "
                f"[{scene.video_query}] "
                f"{scene.narrator_text[:60]}..."
            )

        # ── Steps 3–4: Process each scene ──
        final_scene_paths = []

        for scene in script.scenes:
            log.info("=" * 60)
            log.info(f"SCENE {scene.number}/{len(script.scenes)}")
            log.info("=" * 60)

            # ── 3a: Generate audio and measure exact duration ──
            log.info(f"  [Audio] Generating narration...")
            audio_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_audio.wav"
            )
            duration = self.audio_engine.generate_audio(scene.narrator_text, audio_path)
            scene.audio_path = audio_path
            scene.audio_duration = duration
            log.info(f"  [Audio] Exact duration: {duration:.3f} seconds")

            # ── 3b: Download stock video ──
            log.info(f"  [Video] Searching '{scene.video_query}' on Pexels...")
            raw_video_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_raw.mp4"
            )
            success = search_and_download_video(
                scene.video_query,
                self.pexels_api_key,
                raw_video_path,
                target_duration=duration,
            )

            if not success:
                log.error(
                    f"  Could not get video for scene {scene.number}. "
                    f"Generating black fallback video."
                )
                raw_video_path = self._generate_black_video(duration, raw_video_path)

            scene.video_path = raw_video_path

            # ── 3c: Fit video + mix audio in a single encode pass ──
            log.info(f"  [Assembly] Encoding video + audio in one pass...")
            scene_final_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_final.mp4"
            )
            assemble_scene_from_raw(
                raw_video_path, audio_path, duration, scene_final_path
            )
            final_scene_paths.append(scene_final_path)

            log.info(f"  Scene {scene.number} complete.")

        # ── Step 5: Concatenate all scenes ──
        log.info("=" * 60)
        log.info("STEP 5/5: Concatenating all scenes...")
        log.info("=" * 60)

        # Ensure output directory exists
        output_dir = os.path.dirname(self.output_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        if len(final_scene_paths) == 1:
            # Only one scene: copy directly
            import shutil
            shutil.copy2(final_scene_paths[0], self.output_path)
        else:
            concatenate_scenes(final_scene_paths, self.output_path)

        log.info("=" * 60)
        log.info(f"FINAL VIDEO: {self.output_path}")
        log.info(f"Temporary files in: {self.temp_dir}")
        log.info("=" * 60)

        return self.output_path

    def _generate_black_video(self, duration: float, output_path: str) -> str:
        """Generates a black video as fallback when Pexels fails."""
        clip = ColorClip(
            size=(TARGET_WIDTH, TARGET_HEIGHT),
            color=(0, 0, 0),
            duration=duration,
        )
        clip = clip.with_fps(TARGET_FPS)
        clip.write_videofile(
            output_path,
            codec="libx264",
            audio=False,
            preset=TARGET_PRESET,
            logger=None,
        )
        clip.close()
        return output_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="FreeVi - Automatically generate videos from a PDF",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python freevi.py document.pdf
  python freevi.py book.pdf --model qwen3 --voice af_heart --lang a --output result.mp4

Available languages (--lang):
  a = English (American)    b = English (British)
  e = Spanish               f = French
  h = Hindi                 i = Italian
  j = Japanese              p = Portuguese (Brazilian)
  z = Chinese (Mandarin)

Prerequisites:
  1. Ollama running: ollama serve
  2. Model downloaded: ollama pull qwen3
  3. Kokoro models in ./kokoro-v1.0/
  4. Environment variable: export PEXELS_API_KEY='your_key'
        """,
    )

    parser.add_argument(
        "pdf",
        help="Path to the input PDF file",
    )
    parser.add_argument(
        "--model",
        default="qwen3",
        help="Ollama model to use (default: qwen3)",
    )
    parser.add_argument(
        "--voice",
        default="af_heart",
        help="Kokoro voice ID (default: af_heart). Must match --lang.",
    )
    parser.add_argument(
        "--lang",
        default="a",
        choices=list(KOKORO_LANGUAGES.keys()),
        help="Narration language code (default: a = English American). "
             "Choices: " + ", ".join(
                 f"{k}={v['label']}" for k, v in KOKORO_LANGUAGES.items()
             ),
    )
    parser.add_argument(
        "--speed",
        type=float,
        default=1.0,
        help="Narration speed, 1.0 = normal (default: 1.0)",
    )
    parser.add_argument(
        "--output",
        default="output/video_final.mp4",
        help="Output video path (default: output/video_final.mp4)",
    )
    parser.add_argument(
        "--max-scenes",
        type=int,
        default=8,
        help="Maximum number of scenes to generate (default: 8)",
    )
    parser.add_argument(
        "--context-size",
        type=int,
        default=8192,
        help="Ollama context window size in tokens (default: 8192)",
    )

    args = parser.parse_args()

    log.info("=" * 60)
    log.info("  FreeVi - Video Generator from PDF")
    log.info("=" * 60)
    log.info(f"  PDF:          {args.pdf}")
    log.info(f"  Model:        {args.model}")
    log.info(f"  Language:     {args.lang} ({get_language_label(args.lang)})")
    log.info(f"  Voice:        {args.voice}")
    log.info(f"  Speed:        {args.speed}")
    log.info(f"  Max scenes:   {args.max_scenes}")
    log.info(f"  Context size: {args.context_size}")
    log.info(f"  Output:       {args.output}")
    log.info("=" * 60)

    try:
        generator = VideoGenerator(
            pdf_path=args.pdf,
            llm_model=args.model,
            voice=args.voice,
            voice_speed=args.speed,
            output_path=args.output,
            max_scenes=args.max_scenes,
            context_size=args.context_size,
            lang_code=args.lang,
        )
        final_path = generator.run()
        log.info(f"\nVideo generated successfully: {final_path}")

    except FileNotFoundError as e:
        log.error(f"\nFile not found: {e}")
        sys.exit(1)
    except ConnectionError as e:
        log.error(f"\nConnection error: {e}")
        sys.exit(1)
    except EnvironmentError as e:
        log.error(f"\nConfiguration error: {e}")
        sys.exit(1)
    except ValueError as e:
        log.error(f"\nData error: {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        log.info("\nProcess interrupted by user.")
        sys.exit(130)
    except Exception as e:
        log.error(f"\nUnexpected error: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
