import argparse
import json
import logging
import os
import re
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import fitz  # PyMuPDF
import numpy as np
import ollama
import requests
import soundfile as sf
from kokoro_onnx import Kokoro
from moviepy import (
    AudioFileClip,
    ColorClip,
    VideoFileClip,
    concatenate_videoclips,
)
from dotenv import load_dotenv

# Load environment variables from a .env file if present (optional)
load_dotenv()

# ---------------------------------------------------------------------------
# Configuration and logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(message)s",
)
log = logging.getLogger("freevi")

# Target resolution for the output video
TARGET_WIDTH = 1920
TARGET_HEIGHT = 1080
TARGET_FPS = 24
TARGET_PRESET = "medium"  # x264 encoding preset

# Directory where Kokoro models are stored (relative to this script)
_env_kokoro = os.environ.get("KOKORO_MODEL_DIR", "")
if _env_kokoro:
    KOKORO_MODEL_DIR = Path(_env_kokoro)
else:
    KOKORO_MODEL_DIR = Path(__file__).parent / "kokoro-v1.0"

KOKORO_ONNX_PATH = KOKORO_MODEL_DIR / "kokoro-v1.0.onnx"
KOKORO_VOICES_PATH = KOKORO_MODEL_DIR / "voices-v1.0.bin"


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------
@dataclass
class Scene:
    """Represents a single scene in the video."""

    number: int
    narrator_text: str
    video_query: str
    audio_path: str = ""
    audio_duration: float = 0.0
    video_path: str = ""
    processed_video_path: str = ""


@dataclass
class Script:
    """Contains all scenes generated by the LLM."""

    scenes: list[Scene] = field(default_factory=list)


# ---------------------------------------------------------------------------
# 1. PDF READING MODULE (PyMuPDF)
# ---------------------------------------------------------------------------
def extract_pdf_text(pdf_path: str) -> str:
    """
    Extracts all text from a PDF file using PyMuPDF.

    Args:
        pdf_path: Path to the PDF file.

    Returns:
        Full text extracted from the PDF.

    Raises:
        FileNotFoundError: If the file does not exist.
        RuntimeError: If the PDF cannot be read.
    """
    path = Path(pdf_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {pdf_path}")

    try:
        doc = fitz.open(str(path))
        pages_text = []
        total_pages = len(doc)
        for page_num, page in enumerate(doc, start=1):
            text = page.get_text("text")
            if text.strip():
                pages_text.append(text.strip())
                log.info(f"  Page {page_num}: {len(text)} characters extracted")
        doc.close()

        result = "\n\n".join(pages_text)
        if not result.strip():
            raise RuntimeError("The PDF contains no extractable text.")

        log.info(f"  Total: {len(result)} characters from {total_pages} pages")
        return result

    except Exception as e:
        raise RuntimeError(f"Error reading PDF: {e}")


# ---------------------------------------------------------------------------
# 2. SCRIPT GENERATION MODULE (Ollama - Local LLM)
# ---------------------------------------------------------------------------
SYSTEM_PROMPT_TPL = """You are an expert scriptwriter for educational and informational videos.
Your task is to convert an academic/informational text into a narrated video script.

STRICT RULES:
- Generate between 4 and {max_scenes} scenes (adjust based on text length).
- Each scene must be self-contained and flow naturally into the next.
- "narrator_text": A paragraph in Spanish, natural and conversational (40-80 words).
  Avoid excessive technical jargon. Imagine speaking to a general audience.
- "video_query": Exactly 1 to 3 words in ENGLISH to search for stock video.
  Must be visually descriptive and concrete (e.g. "ocean waves", "city traffic",
  "laboratory research"). Avoid abstract terms.

RESPOND ONLY with valid JSON in this exact structure:
{{
  "scenes": [
    {{
      "narrator_text": "text in Spanish...",
      "video_query": "english query"
    }}
  ]
}}"""


def _clean_json(text: str) -> str:
    """
    Attempts to extract valid JSON from an LLM response that may include:
    - Markdown code fences (```json ... ```)
    - Preamble text before the JSON
    - Extra text after the JSON
    - Typographic quotes or other minor artifacts

    Returns:
        The most likely JSON string, ready for json.loads().
    """
    # 1. Strip markdown code fences: ```json ... ``` or ``` ... ```
    match = re.search(r"```(?:json)?\s*([\s\S]*?)```", text, re.IGNORECASE)
    if match:
        text = match.group(1).strip()

    # 2. Extract the first balanced JSON object {...}
    start = text.find("{")
    if start == -1:
        return text  # Cannot clean further; let json.loads fail with a clear message

    # Find the matching closing brace
    depth = 0
    for i, c in enumerate(text[start:], start=start):
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]

    # No balanced closing brace found; return from { to end
    return text[start:]


def generate_script(pdf_text: str, model: str = "qwen3", max_scenes: int = 8) -> Script:
    """
    Sends the PDF text to a local LLM via Ollama to generate the video script.

    Uses format='json' to enforce structured JSON output.

    Args:
        pdf_text: Text extracted from the PDF.
        model: Name of the Ollama model to use.
        max_scenes: Maximum number of scenes to generate.

    Returns:
        Script with the list of scenes.

    Raises:
        ConnectionError: If Ollama is not available.
        ValueError: If the response does not have the expected format.
    """
    # Truncate text if too long to avoid exceeding the model's context
    max_chars = 12000
    if len(pdf_text) > max_chars:
        pdf_text = pdf_text[:max_chars] + "\n\n[... text truncated due to length ...]"
        log.warning(f"  Text truncated to {max_chars} characters for the model.")

    system_prompt = SYSTEM_PROMPT_TPL.format(max_scenes=max_scenes)
    user_prompt = (
        f"Convert the following text into a narrated video script:\n\n"
        f"---START OF TEXT---\n{pdf_text}\n---END OF TEXT---"
    )

    try:
        response = ollama.chat(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            format="json",
        )
    except Exception as e:
        raise ConnectionError(
            f"Error connecting to Ollama. Is the server running?\n"
            f"Run: ollama serve\n"
            f"Details: {e}"
        )

    # Parse JSON response
    content = response["message"]["content"]
    log.info(f"  LLM response received ({len(content)} characters)")

    cleaned = _clean_json(content)
    log.debug(f"  JSON after cleaning: {cleaned[:300]}")

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError as e:
        # Last attempt: replace typographic quotes and retry
        cleaned2 = (
            cleaned
            .replace("\u201c", '"').replace("\u201d", '"')  # "" → ""
            .replace("\u2018", "'").replace("\u2019", "'")  # '' → ''
        )
        try:
            data = json.loads(cleaned2)
        except json.JSONDecodeError:
            raise ValueError(
                f"The LLM did not return valid JSON even after attempting to clean the response.\n"
                f"First 500 characters received:\n{content[:500]}\n"
                f"JSON error: {e}"
            )

    # Validate structure — tolerate key name variations from small models
    scenes_list = None
    for key in ("scenes", "escenas", "script", "guion", "video_scenes", "scene"):
        val = data.get(key)
        if isinstance(val, list) and val:
            scenes_list = val
            break
    # If the JSON is directly a list instead of an object
    if scenes_list is None and isinstance(data, list):
        scenes_list = data
    if scenes_list is None:
        raise ValueError(
            f"The JSON does not contain a recognizable list of scenes.\n"
            f"Keys received: {list(data.keys()) if isinstance(data, dict) else type(data)}"
        )

    script = Script()
    for i, raw_scene in enumerate(scenes_list, start=1):
        if not isinstance(raw_scene, dict):
            log.warning(f"  Scene {i}: unexpected element ({type(raw_scene)}), skipping.")
            continue
        # Tolerate field name variations from different models
        narrator_text = (
            raw_scene.get("narrator_text")
            or raw_scene.get("texto_narrador")
            or raw_scene.get("narrator")
            or raw_scene.get("narrador")
            or raw_scene.get("text")
            or ""
        ).strip()
        video_query = (
            raw_scene.get("video_query")
            or raw_scene.get("query")
            or raw_scene.get("visual")
            or raw_scene.get("video")
            or ""
        ).strip()

        if not narrator_text:
            log.warning(f"  Scene {i}: no narrator text, skipping.")
            continue
        if not video_query:
            video_query = "nature landscape"  # Generic fallback
            log.warning(f"  Scene {i}: no video_query, using fallback '{video_query}'")

        # Limit query to 3 words maximum
        video_query = " ".join(video_query.split()[:3])

        script.scenes.append(
            Scene(number=i, narrator_text=narrator_text, video_query=video_query)
        )

    if not script.scenes:
        raise ValueError("The LLM did not generate any valid scenes.")

    log.info(f"  Script generated: {len(script.scenes)} scenes")
    return script


# ---------------------------------------------------------------------------
# 3. AUDIO MODULE (Kokoro 1.0 via kokoro-onnx)
# ---------------------------------------------------------------------------
class AudioEngine:
    """
    Generates TTS audio using Kokoro 1.0 with ONNX Runtime.

    Uses misaki EspeakG2P to convert Spanish text to phonemes,
    then Kokoro generates the audio.
    """

    def __init__(self, voice: str = "im_nicola", speed: float = 1.0):
        """
        Initializes the audio engine.

        Args:
            voice: Kokoro voice name (im_nicola for Spanish).
            speed: Speech speed (1.0 = normal).
        """
        self.voice = voice
        self.speed = speed
        self.kokoro = None
        self.g2p = None

    def _initialize(self):
        """Loads the Kokoro model and G2P module (lazy loading)."""
        if self.kokoro is not None:
            return

        # Verify model files exist
        if not KOKORO_ONNX_PATH.exists():
            raise FileNotFoundError(
                f"Kokoro model not found at: {KOKORO_ONNX_PATH}\n"
                f"Download it from: https://github.com/thewh1teagle/kokoro-onnx/releases"
            )
        if not KOKORO_VOICES_PATH.exists():
            raise FileNotFoundError(
                f"Kokoro voices not found at: {KOKORO_VOICES_PATH}\n"
                f"Download them from: https://github.com/thewh1teagle/kokoro-onnx/releases"
            )

        log.info("  Loading Kokoro v1.0 model (this may take a few seconds)...")
        self.kokoro = Kokoro(str(KOKORO_ONNX_PATH), str(KOKORO_VOICES_PATH))

        # Initialize G2P for Spanish with misaki + espeak-ng
        try:
            from misaki.espeak import EspeakG2P

            self.g2p = EspeakG2P(language="es")
            log.info("  Spanish G2P initialized (misaki + espeak-ng)")
        except ImportError:
            log.warning(
                "  misaki not available. Using direct mode (no phonemization).\n"
                "  For better Spanish quality: pip install misaki"
            )
            self.g2p = None

    def generate_audio(self, text: str, output_path: str) -> float:
        """
        Generates a .wav file from Spanish text.

        Args:
            text: Spanish text to synthesize.
            output_path: Path where the .wav file will be saved.

        Returns:
            Exact audio duration in seconds.
        """
        self._initialize()

        try:
            if self.g2p is not None:
                # Convert text to phonemes for better Spanish quality
                # misaki 0.7+ EspeakG2P returns str directly
                phonemes = self.g2p(text)
                if not phonemes:
                    log.warning("  G2P returned empty phonemes, using text directly.")
                    phonemes = text
                samples, sample_rate = self.kokoro.create(
                    phonemes,
                    voice=self.voice,
                    speed=self.speed,
                    is_phonemes=True,
                )
            else:
                # Direct mode (no phonemization, reduced quality for Spanish)
                samples, sample_rate = self.kokoro.create(
                    text,
                    voice=self.voice,
                    speed=self.speed,
                    lang="es",
                )

            # Save audio
            sf.write(output_path, samples, sample_rate)

            # Calculate exact duration from samples
            duration = len(samples) / sample_rate
            log.info(
                f"  Audio generated: {duration:.2f}s "
                f"({len(samples)} samples @ {sample_rate}Hz)"
            )
            return duration

        except Exception as e:
            raise RuntimeError(f"Error generating audio with Kokoro: {e}")


# ---------------------------------------------------------------------------
# 4. VISUAL MODULE (Pexels API - 100% Free)
# ---------------------------------------------------------------------------
PEXELS_API_URL = "https://api.pexels.com/videos/search"


def get_pexels_api_key() -> str:
    """
    Retrieves the Pexels API key from environment variable.

    Returns:
        The API key.

    Raises:
        EnvironmentError: If the variable is not set.
    """
    api_key = os.environ.get("PEXELS_API_KEY", "")
    if not api_key:
        raise EnvironmentError(
            "PEXELS_API_KEY environment variable is not set.\n"
            "Get a free key at: https://www.pexels.com/api/\n"
            "Set it with: export PEXELS_API_KEY='your_key_here'"
        )
    return api_key


def search_pexels_video(query: str, api_key: str, orientation: str = "landscape") -> dict | None:
    """
    Searches for a video on Pexels and returns info about the best result.

    Args:
        query: Search terms in English (max 3 words).
        api_key: Pexels API key.
        orientation: "landscape", "portrait" or "square".

    Returns:
        Dict with 'url' (download link), 'width', 'height', 'duration' or None.
    """
    headers = {"Authorization": api_key}
    params = {
        "query": query,
        "per_page": 5,
        "orientation": orientation,
        "size": "medium",  # Balance between quality and file size
    }

    try:
        resp = requests.get(PEXELS_API_URL, headers=headers, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except requests.exceptions.RequestException as e:
        log.error(f"  Pexels API error: {e}")
        return None

    videos = data.get("videos", [])
    if not videos:
        log.warning(f"  No videos found for '{query}'")
        return None

    # Select the first video with available files
    for video in videos:
        files = video.get("video_files", [])
        # Prefer HD (1280x720 or higher) in mp4
        best = None
        for file in files:
            if file.get("file_type") != "video/mp4":
                continue
            w = file.get("width", 0)
            h = file.get("height", 0)
            # Prefer resolutions >= 720p
            if w >= 1280 and h >= 720:
                if best is None or w < best.get("width", 9999):
                    # Take the smallest that is >= HD (faster download)
                    best = file

        # If no HD found, take the first available mp4
        if best is None:
            for file in files:
                if file.get("file_type") == "video/mp4":
                    best = file
                    break

        if best:
            return {
                "url": best["link"],
                "width": best.get("width", 0),
                "height": best.get("height", 0),
                "duration": video.get("duration", 0),
            }

    log.warning(f"  No mp4 files found for '{query}'")
    return None


def download_video(url: str, output_path: str) -> bool:
    """
    Downloads a video from a URL.

    Args:
        url: Direct URL of the video file.
        output_path: Local path where the file will be saved.

    Returns:
        True if the download was successful.
    """
    try:
        log.info(f"  Downloading video...")
        resp = requests.get(url, stream=True, timeout=60)
        resp.raise_for_status()

        total_size = int(resp.headers.get("content-length", 0))
        downloaded = 0

        with open(output_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=1024 * 1024):  # 1MB chunks
                f.write(chunk)
                downloaded += len(chunk)

        size_mb = downloaded / (1024 * 1024)
        log.info(f"  Downloaded: {size_mb:.1f} MB → {output_path}")
        return True

    except requests.exceptions.RequestException as e:
        log.error(f"  Error downloading video: {e}")
        return False


def search_and_download_video(query: str, api_key: str, output_path: str) -> bool:
    """
    Searches and downloads a video from Pexels. If the main query fails,
    tries generic fallbacks.

    Args:
        query: Original search terms.
        api_key: Pexels API key.
        output_path: Path where the video will be saved.

    Returns:
        True if downloaded successfully.
    """
    # Try with the original query
    info = search_pexels_video(query, api_key)

    # Fallbacks if the original query yields no results
    if info is None:
        fallbacks = ["nature", "abstract background", "technology"]
        for fb in fallbacks:
            log.info(f"  Trying fallback: '{fb}'")
            info = search_pexels_video(fb, api_key)
            if info is not None:
                break

    if info is None:
        log.error(f"  Could not find any video (query: '{query}')")
        return False

    return download_video(info["url"], output_path)


# ---------------------------------------------------------------------------
# 5. ASSEMBLY MODULE (MoviePy)
# ---------------------------------------------------------------------------
def fit_video_to_duration(video_path: str, target_duration: float, output_path: str) -> str:
    """
    Adjusts a stock video to match the exact audio duration.

    If the video is longer → trim it (subclip).
    If the video is shorter → loop it until it covers the duration.

    Also resizes to TARGET_WIDTH x TARGET_HEIGHT if needed.

    Args:
        video_path: Path to the video downloaded from Pexels.
        target_duration: Exact duration in seconds (from audio).
        output_path: Path where the processed video will be saved.

    Returns:
        Path to the processed video.
    """
    clip = VideoFileClip(video_path)
    video_duration = clip.duration

    log.info(
        f"  Original video: {video_duration:.2f}s → "
        f"Target: {target_duration:.2f}s"
    )

    if video_duration >= target_duration:
        # Video is longer: trim it
        adjusted = clip.subclipped(0, target_duration)
    else:
        # Video is shorter: loop it
        repetitions = int(target_duration / video_duration) + 1
        adjusted = concatenate_videoclips([clip] * repetitions, method="compose")
        adjusted = adjusted.subclipped(0, target_duration)

    # Resize to target resolution if needed
    w, h = adjusted.size
    if w != TARGET_WIDTH or h != TARGET_HEIGHT:
        adjusted = adjusted.resized(new_size=(TARGET_WIDTH, TARGET_HEIGHT))

    # Set target FPS
    adjusted = adjusted.with_fps(TARGET_FPS)

    adjusted.write_videofile(
        output_path,
        codec="libx264",
        audio=False,  # Audio is added later
        preset=TARGET_PRESET,
        logger=None,  # Suppress ffmpeg output
    )

    clip.close()
    adjusted.close()

    log.info(f"  Adjusted video saved: {output_path}")
    return output_path


def assemble_scene(scene: Scene, output_path: str) -> str:
    """
    Combines the processed video with the audio for a scene.

    Args:
        scene: Scene with audio and processed video paths.
        output_path: Path for the final scene video file.

    Returns:
        Path to the assembled video.
    """
    video = VideoFileClip(scene.processed_video_path)
    audio = AudioFileClip(scene.audio_path)

    video_with_audio = video.with_audio(audio)

    video_with_audio.write_videofile(
        output_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )

    video.close()
    audio.close()
    video_with_audio.close()

    log.info(f"  Scene assembled: {output_path}")
    return output_path


def concatenate_scenes(scene_paths: list[str], final_path: str) -> str:
    """
    Concatenates all scenes into a single final video.

    Args:
        scene_paths: List of paths to each scene's video file.
        final_path: Output path for the final video.

    Returns:
        Path to the final video.
    """
    clips = [VideoFileClip(path) for path in scene_paths]

    final_video = concatenate_videoclips(clips, method="compose")
    final_video.write_videofile(
        final_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )

    for clip in clips:
        clip.close()
    final_video.close()

    log.info(f"Final video generated: {final_path}")
    return final_path


# ---------------------------------------------------------------------------
# 6. MAIN ORCHESTRATOR
# ---------------------------------------------------------------------------
class VideoGenerator:
    """
    Orchestrates the entire video generation pipeline.

    Per-scene pipeline (strict order for synchronization):
      1. LLM generates narrator text + visual query
      2. Kokoro generates audio → exact duration is measured
      3. Pexels downloads video → trimmed/looped to that duration
      4. MoviePy combines audio + video
      5. All scenes are concatenated at the end
    """

    def __init__(
        self,
        pdf_path: str,
        llm_model: str = "qwen3",
        voice: str = "im_nicola",
        voice_speed: float = 1.0,
        output_path: str = "output/video_final.mp4",
    ):
        self.pdf_path = pdf_path
        self.llm_model = llm_model
        self.output_path = output_path
        self.audio_engine = AudioEngine(voice=voice, speed=voice_speed)
        self.pexels_api_key = get_pexels_api_key()
        self.temp_dir = tempfile.mkdtemp(prefix="freevi_")
        log.info(f"Temporary directory: {self.temp_dir}")

    def run(self):
        """Runs the full pipeline."""
        # ── Step 1: Extract PDF text ──
        log.info("=" * 60)
        log.info("STEP 1/5: Extracting text from PDF...")
        log.info("=" * 60)
        pdf_text = extract_pdf_text(self.pdf_path)

        # ── Step 2: Generate script with LLM ──
        log.info("=" * 60)
        log.info(f"STEP 2/5: Generating script with {self.llm_model}...")
        log.info("=" * 60)
        script = generate_script(pdf_text, self.llm_model)

        # Show script summary
        for scene in script.scenes:
            log.info(
                f"  Scene {scene.number}: "
                f"[{scene.video_query}] "
                f"{scene.narrator_text[:60]}..."
            )

        # ── Steps 3–4: Process each scene ──
        final_scene_paths = []

        for scene in script.scenes:
            log.info("=" * 60)
            log.info(f"SCENE {scene.number}/{len(script.scenes)}")
            log.info("=" * 60)

            # ── 3a: Generate audio and measure exact duration ──
            log.info(f"  [Audio] Generating narration...")
            audio_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_audio.wav"
            )
            duration = self.audio_engine.generate_audio(scene.narrator_text, audio_path)
            scene.audio_path = audio_path
            scene.audio_duration = duration
            log.info(f"  [Audio] Exact duration: {duration:.3f} seconds")

            # ── 3b: Download stock video ──
            log.info(f"  [Video] Searching '{scene.video_query}' on Pexels...")
            raw_video_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_raw.mp4"
            )
            success = search_and_download_video(
                scene.video_query, self.pexels_api_key, raw_video_path
            )

            if not success:
                log.error(
                    f"  Could not get video for scene {scene.number}. "
                    f"Generating black fallback video."
                )
                raw_video_path = self._generate_black_video(duration, raw_video_path)

            scene.video_path = raw_video_path

            # ── 3c: Fit video to exact audio duration ──
            log.info(f"  [Video] Fitting to {duration:.3f}s...")
            processed_video_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_processed.mp4"
            )
            fit_video_to_duration(raw_video_path, duration, processed_video_path)
            scene.processed_video_path = processed_video_path

            # ── 3d: Assemble audio + video for this scene ──
            log.info(f"  [Assembly] Combining audio + video...")
            scene_final_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_final.mp4"
            )
            assemble_scene(scene, scene_final_path)
            final_scene_paths.append(scene_final_path)

            log.info(f"  Scene {scene.number} complete.")

        # ── Step 5: Concatenate all scenes ──
        log.info("=" * 60)
        log.info("STEP 5/5: Concatenating all scenes...")
        log.info("=" * 60)

        # Ensure output directory exists
        output_dir = os.path.dirname(self.output_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        if len(final_scene_paths) == 1:
            # Only one scene: copy directly
            import shutil
            shutil.copy2(final_scene_paths[0], self.output_path)
        else:
            concatenate_scenes(final_scene_paths, self.output_path)

        log.info("=" * 60)
        log.info(f"FINAL VIDEO: {self.output_path}")
        log.info(f"Temporary files in: {self.temp_dir}")
        log.info("=" * 60)

        return self.output_path

    def _generate_black_video(self, duration: float, output_path: str) -> str:
        """Generates a black video as fallback when Pexels fails."""
        clip = ColorClip(
            size=(TARGET_WIDTH, TARGET_HEIGHT),
            color=(0, 0, 0),
            duration=duration,
        )
        clip = clip.with_fps(TARGET_FPS)
        clip.write_videofile(
            output_path,
            codec="libx264",
            audio=False,
            logger=None,
        )
        clip.close()
        return output_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="FreeVi - Automatically generate videos from a PDF",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python freevi.py document.pdf
  python freevi.py book.pdf --model qwen3 --voice im_nicola --output result.mp4

Prerequisites:
  1. Ollama running: ollama serve
  2. Model downloaded: ollama pull qwen3
  3. Kokoro models in ./kokoro-v1.0/
  4. Environment variable: export PEXELS_API_KEY='your_key'
        """,
    )

    parser.add_argument(
        "pdf",
        help="Path to the input PDF file",
    )
    parser.add_argument(
        "--model",
        default="qwen3",
        help="Ollama model to use (default: qwen3)",
    )
    parser.add_argument(
        "--voice",
        default="im_nicola",
        help="Kokoro voice for Spanish narration (default: im_nicola)",
    )
    parser.add_argument(
        "--speed",
        type=float,
        default=1.0,
        help="Narration speed, 1.0 = normal (default: 1.0)",
    )
    parser.add_argument(
        "--output",
        default="output/video_final.mp4",
        help="Output video path (default: output/video_final.mp4)",
    )

    args = parser.parse_args()

    log.info("=" * 60)
    log.info("  FreeVi - Video Generator from PDF")
    log.info("=" * 60)
    log.info(f"  PDF:    {args.pdf}")
    log.info(f"  Model:  {args.model}")
    log.info(f"  Voice:  {args.voice}")
    log.info(f"  Speed:  {args.speed}")
    log.info(f"  Output: {args.output}")
    log.info("=" * 60)

    try:
        generator = VideoGenerator(
            pdf_path=args.pdf,
            llm_model=args.model,
            voice=args.voice,
            voice_speed=args.speed,
            output_path=args.output,
        )
        final_path = generator.run()
        log.info(f"\nVideo generated successfully: {final_path}")

    except FileNotFoundError as e:
        log.error(f"\nFile not found: {e}")
        sys.exit(1)
    except ConnectionError as e:
        log.error(f"\nConnection error: {e}")
        sys.exit(1)
    except EnvironmentError as e:
        log.error(f"\nConfiguration error: {e}")
        sys.exit(1)
    except ValueError as e:
        log.error(f"\nData error: {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        log.info("\nProcess interrupted by user.")
        sys.exit(130)
    except Exception as e:
        log.error(f"\nUnexpected error: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
