import argparse
import json
import logging
import os
import re
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import fitz  # PyMuPDF
import ollama
import requests
import soundfile as sf
from kokoro_onnx import Kokoro
from moviepy import (
    AudioFileClip,
    ColorClip,
    VideoFileClip,
    concatenate_videoclips,
)
from dotenv import load_dotenv

# Load environment variables from a .env file if present (optional)
load_dotenv()

# ---------------------------------------------------------------------------
# Configuration and logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s] %(message)s",
)
log = logging.getLogger("freevi")

# Target resolution for the output video
TARGET_WIDTH = 1920
TARGET_HEIGHT = 1080
TARGET_FPS = 24
TARGET_PRESET = "medium"  # x264 encoding preset

# Directory where Kokoro models are stored (relative to this script)
_env_kokoro = os.environ.get("KOKORO_MODEL_DIR", "")
if _env_kokoro:
    KOKORO_MODEL_DIR = Path(_env_kokoro)
else:
    KOKORO_MODEL_DIR = Path(__file__).parent / "kokoro-v1.0"

KOKORO_ONNX_PATH = KOKORO_MODEL_DIR / "kokoro-v1.0.onnx"
KOKORO_VOICES_PATH = KOKORO_MODEL_DIR / "voices-v1.0.bin"


# ---------------------------------------------------------------------------
# Kokoro 1.0 language and voice registry
# ---------------------------------------------------------------------------
# Each key is a Kokoro lang_code (single char), mapped to metadata and voices.
# The espeak_code is passed to misaki EspeakG2P (or None for non-espeak G2P).
# Voices are ordered: females first, then males, alphabetically.

KOKORO_LANGUAGES: dict[str, dict] = {
    "a": {
        "label": "English (American)",
        "espeak_code": "en-us",
        "voices": [
            "af_alloy", "af_aoede", "af_bella", "af_heart", "af_jessica",
            "af_kore", "af_nicole", "af_nova", "af_river", "af_sarah", "af_sky",
            "am_adam", "am_echo", "am_eric", "am_fenrir", "am_liam",
            "am_michael", "am_onyx", "am_puck", "am_santa",
        ],
    },
    "b": {
        "label": "English (British)",
        "espeak_code": "en-gb",
        "voices": [
            "bf_alice", "bf_emma", "bf_isabella", "bf_lily",
            "bm_daniel", "bm_fable", "bm_george", "bm_lewis",
        ],
    },
    "e": {
        "label": "Spanish",
        "espeak_code": "es",
        "voices": ["ef_dora", "em_alex", "em_santa"],
    },
    "f": {
        "label": "French",
        "espeak_code": "fr-fr",
        "voices": ["ff_siwis"],
    },
    "h": {
        "label": "Hindi",
        "espeak_code": "hi",
        "voices": ["hf_alpha", "hf_beta", "hm_omega", "hm_psi"],
    },
    "i": {
        "label": "Italian",
        "espeak_code": "it",
        "voices": ["if_sara", "im_nicola"],
    },
    "j": {
        "label": "Japanese",
        "espeak_code": None,  # uses misaki[ja], not espeak
        "voices": [
            "jf_alpha", "jf_gongitsune", "jf_nezumi", "jf_tebukuro",
            "jm_kumo",
        ],
    },
    "p": {
        "label": "Portuguese (Brazilian)",
        "espeak_code": "pt-br",
        "voices": ["pf_dora", "pm_alex", "pm_santa"],
    },
    "z": {
        "label": "Chinese (Mandarin)",
        "espeak_code": None,  # uses misaki[zh], not espeak
        "voices": [
            "zf_xiaobei", "zf_xiaoni", "zf_xiaoxiao", "zf_xiaoyi",
            "zm_yunjian", "zm_yunxi", "zm_yunxia", "zm_yunyang",
        ],
    },
}

# Reverse lookup: voice_id → lang_code
_VOICE_TO_LANG: dict[str, str] = {}
for _lc, _info in KOKORO_LANGUAGES.items():
    for _v in _info["voices"]:
        _VOICE_TO_LANG[_v] = _lc


def get_lang_code_for_voice(voice: str) -> str:
    """Returns the Kokoro lang_code ('a', 'e', 'i', ...) for a given voice ID."""
    return _VOICE_TO_LANG.get(voice, voice[0] if voice else "a")


def get_voices_for_lang(lang_code: str) -> list[str]:
    """Returns the list of voice IDs available for a given lang_code."""
    info = KOKORO_LANGUAGES.get(lang_code)
    return list(info["voices"]) if info else []


def get_language_label(lang_code: str) -> str:
    """Returns the human-readable label for a Kokoro lang_code."""
    info = KOKORO_LANGUAGES.get(lang_code)
    return info["label"] if info else lang_code


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------
@dataclass
class Scene:
    """Represents a single scene in the video."""

    number: int
    narrator_text: str
    video_query: str
    audio_path: str = ""
    audio_duration: float = 0.0
    video_path: str = ""
    processed_video_path: str = ""


@dataclass
class Script:
    """Contains all scenes generated by the LLM."""

    scenes: list[Scene] = field(default_factory=list)
    # Effective number of scenes after chunk-alignment adjustment.
    # May differ from the max_scenes the user requested.
    adjusted_max_scenes: int = 0
    # Number of PDF chunks the text was split into.
    n_chunks: int = 0


# ---------------------------------------------------------------------------
# 1. PDF READING MODULE (PyMuPDF)
# ---------------------------------------------------------------------------
def extract_pdf_text(pdf_path: str) -> str:
    """
    Extracts all text from a PDF file using PyMuPDF.

    Args:
        pdf_path: Path to the PDF file.

    Returns:
        Full text extracted from the PDF.

    Raises:
        FileNotFoundError: If the file does not exist.
        RuntimeError: If the PDF cannot be read.
    """
    path = Path(pdf_path)
    if not path.exists():
        raise FileNotFoundError(f"File not found: {pdf_path}")

    try:
        doc = fitz.open(str(path))
        pages_text = []
        total_pages = len(doc)
        for page_num, page in enumerate(doc, start=1):
            text = page.get_text("text")
            if text.strip():
                pages_text.append(text.strip())
                log.info(f"  Page {page_num}: {len(text)} characters extracted")
        doc.close()

        result = "\n\n".join(pages_text)
        if not result.strip():
            raise RuntimeError("The PDF contains no extractable text.")

        log.info(f"  Total: {len(result)} characters from {total_pages} pages")
        return result

    except Exception as e:
        raise RuntimeError(f"Error reading PDF: {e}")


# ---------------------------------------------------------------------------
# 2. SCRIPT GENERATION MODULE (Ollama - Local LLM)
# ---------------------------------------------------------------------------

# The part the user can freely customise in the GUI.
# It is injected between the role description and the strict JSON rules,
# so even if the user clears it completely the pipeline keeps working.
DEFAULT_CUSTOM_INSTRUCTIONS = """\
- Keep the narration natural and conversational (40-80 words per scene).
- Avoid excessive technical jargon. Imagine speaking to a general audience.\
"""

# Fixed parts that must always be present for the pipeline to work.
# {max_scenes} and {narration_language} are replaced at runtime.
# {{ / }} are literal braces in the JSON example.
_SYSTEM_PROMPT_HEAD = """\
You are an expert scriptwriter for educational and informational videos.
Your task is to convert an academic/informational text into a narrated video script.

MANDATORY LANGUAGE RULE (NON-NEGOTIABLE):
- ALL narrator_text MUST be written in **{narration_language}**.
- This is an absolute requirement. Do NOT write narrator_text in any other language.
- Even if the source text is in a different language, translate and narrate in {narration_language}.

STRICT RULES:
- Generate between 4 and {max_scenes} scenes (adjust based on text length).
- Each scene must be self-contained and flow naturally into the next.
- "narrator_text": The narration text for this scene (MUST be in {narration_language}).
- "video_query": 2 to 5 words in ENGLISH to search for a stock video clip.
  CRITICAL: The query MUST visually represent the specific subject of THAT scene's
  narrator_text, not the document topic in general.
  Ask yourself: "What does a camera show while the narrator says this sentence?"
  Rules for the query:
    * Be concrete and visual — name objects, actions, or settings that can be filmed.
    * Match the scene content — if the narrator discusses data analysis, write
      "data analyst working computer", not "technology".
    * Use 3-5 words for specificity; single generic words produce unrelated footage.
    * Write in English regardless of the narration language.
  Good examples:  "scientists analyzing dna samples", "city traffic aerial view",
                  "students working laptops classroom", "factory assembly line robots"
  Bad examples:   "technology", "science", "research", "nature landscape"\
"""

_SYSTEM_PROMPT_TAIL = """\

RESPOND ONLY with valid JSON in this exact structure:
{{
  "scenes": [
    {{
      "narrator_text": "narration text in {narration_language}...",
      "video_query": "scientists analyzing data results"
    }},
    {{
      "narrator_text": "more narration in {narration_language}...",
      "video_query": "city traffic aerial view"
    }}
  ]
}}\
"""

# Legacy alias kept so any code that imports SYSTEM_PROMPT_TPL still works.
SYSTEM_PROMPT_TPL = _SYSTEM_PROMPT_HEAD + "\n{custom_instructions}\n" + _SYSTEM_PROMPT_TAIL


def build_system_prompt(
    max_scenes: int,
    custom_instructions: str = "",
    narration_language: str = "Spanish",
    chunk_header: str = "",
) -> str:
    """
    Assembles the final system prompt from the fixed parts and the
    user-supplied custom instructions.

    The custom instructions are sandwiched between the role/rules header and
    the mandatory JSON format block, so:
      - An empty string is perfectly valid (the pipeline still works).
      - The user cannot accidentally remove the JSON format requirement.
      - The user can change tone, length, etc. freely.
      - The narration language is enforced in the fixed parts and cannot be
        overridden by the user's custom instructions.

    Args:
        max_scenes: Maximum number of scenes to request from the LLM.
        custom_instructions: Free-form text from the GUI prompt editor.
                             Defaults to DEFAULT_CUSTOM_INSTRUCTIONS.
        narration_language: The language name in English (e.g. "Spanish",
                           "English (American)") injected into the prompt
                           so the LLM is forced to narrate in it.
        chunk_header: Optional multi-chunk context injected at the end of the
                      head (e.g. "Part 2 of 5. Previously narrated: …").
                      Empty string means single-chunk mode.

    Returns:
        The complete system prompt string ready to send to Ollama.
    """
    instructions = custom_instructions.strip() or DEFAULT_CUSTOM_INSTRUCTIONS
    head = _SYSTEM_PROMPT_HEAD.format(
        max_scenes=max_scenes,
        narration_language=narration_language,
    )
    if chunk_header:
        head = head + f"\n\nDOCUMENT CHUNK CONTEXT:\n{chunk_header}"
    tail = _SYSTEM_PROMPT_TAIL.format(narration_language=narration_language)
    return f"{head}\n\n{instructions}\n{tail}"


def _clean_json(text: str) -> str:
    """
    Attempts to extract valid JSON from an LLM response that may include:
    - Markdown code fences (```json ... ```)
    - Preamble text before the JSON
    - Extra text after the JSON
    - Typographic quotes or other minor artifacts

    Returns:
        The most likely JSON string, ready for json.loads().
    """
    # 1. Strip markdown code fences: ```json ... ``` or ``` ... ```
    match = re.search(r"```(?:json)?\s*([\s\S]*?)```", text, re.IGNORECASE)
    if match:
        text = match.group(1).strip()

    # 2. Extract the first balanced JSON object {...}
    start = text.find("{")
    if start == -1:
        return text  # Cannot clean further; let json.loads fail with a clear message

    # Find the matching closing brace
    depth = 0
    for i, c in enumerate(text[start:], start=start):
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]

    # No balanced closing brace found; return from { to end
    return text[start:]


# ---------------------------------------------------------------------------
# Chunk-based script generation helpers
# ---------------------------------------------------------------------------

# Keywords that identify thinking/reasoning models (case-insensitive substring
# match against the model name).
_THINKING_KEYWORDS = ("thinking", "think", "qwq", "r1", "reasoner")

# Tokens consumed by the internal reasoning chain of thinking models before
# they write the actual JSON output.
_THINKING_OVERHEAD = 2048

# Tokens reserved for the system prompt and user message wrappers.
_SYSTEM_PROMPT_TOKENS = 400

# Tokens reserved per scene for JSON output (narrator_text + video_query +
# JSON scaffolding).  800 tokens is sufficient for verbose models like
# gemma3 whose narrator_text can easily reach 600–700 tokens per scene.
_TOKENS_PER_SCENE = 800

# Minimum JSON output budget regardless of scene count.
_OUTPUT_BASE_TOKENS = 512

# Characters per token estimate (conservative, works for mixed-language text).
_CHARS_PER_TOKEN = 3


def _is_thinking_model(model: str) -> bool:
    """Returns True if the model name suggests it uses a reasoning/thinking chain."""
    return any(kw in model.lower() for kw in _THINKING_KEYWORDS)


def _next_power_of_two(n: int) -> int:
    """Returns the smallest power of two that is >= n."""
    p = 1
    while p < n:
        p <<= 1
    return p


def _calculate_context_size(chunk_tokens: int, scenes_per_chunk: int,
                             thinking: bool) -> int:
    """
    Derives the Ollama num_ctx that comfortably fits one chunk call.

    Formula:
        raw = chunk_tokens + output_budget + system_tokens + thinking_overhead
        context_size = next power of two >= raw

    The result is rounded up to a power of two so Ollama uses a clean KV-cache
    size, which also gives a small extra safety margin.

    Args:
        chunk_tokens: Number of input tokens for the PDF chunk.
        scenes_per_chunk: How many scenes will be requested in this call.
        thinking: Whether the model uses an internal reasoning chain.

    Returns:
        Recommended num_ctx value.
    """
    output_budget = scenes_per_chunk * _TOKENS_PER_SCENE + _OUTPUT_BASE_TOKENS
    thinking_extra = _THINKING_OVERHEAD if thinking else 0
    raw = chunk_tokens + output_budget + _SYSTEM_PROMPT_TOKENS + thinking_extra
    return _next_power_of_two(raw)


def _split_into_chunks(text: str, max_chars: int) -> list[str]:
    """
    Splits *text* into chunks of at most *max_chars* characters each.

    Prefers to cut at paragraph boundaries (double newline).  Falls back to
    sentence boundaries ('. ') if no paragraph break is found.  Hard-cuts at
    *max_chars* as a last resort so no chunk ever exceeds the limit.

    Args:
        text: The full text to split.
        max_chars: Maximum characters per chunk.

    Returns:
        List of non-empty text chunks.
    """
    if len(text) <= max_chars:
        return [text]

    chunks: list[str] = []
    remaining = text
    while remaining:
        if len(remaining) <= max_chars:
            chunks.append(remaining)
            break

        # Try to cut at the last paragraph break within the window
        window = remaining[:max_chars]
        cut = window.rfind("\n\n")
        if cut == -1:
            # Fall back to last sentence boundary
            cut = window.rfind(". ")
            if cut != -1:
                cut += 1  # include the period
        if cut == -1:
            # Hard cut
            cut = max_chars

        chunks.append(remaining[:cut].rstrip())
        remaining = remaining[cut:].lstrip()

    return [c for c in chunks if c]


def count_chunks(pdf_text: str, chunk_tokens: int) -> int:
    """
    Returns the number of chunks that *pdf_text* would be split into for a
    given *chunk_tokens* setting.

    This is a lightweight preview function intended for the GUI so it can
    update the max-scenes spinner in real time without running the full
    pipeline.

    Args:
        pdf_text: Full text extracted from the PDF.
        chunk_tokens: Chunk size in tokens (same as the GUI's chunk_size field).

    Returns:
        Number of chunks (always >= 1).
    """
    max_chars = max(500, chunk_tokens * _CHARS_PER_TOKEN)
    return len(_split_into_chunks(pdf_text, max_chars))


def _summarize_scenes(scenes: list) -> str:
    """
    Builds a short plain-text summary of the most recently generated scenes
    WITHOUT making an extra LLM call.  Used to give the model context about
    what has already been narrated so it does not repeat itself.

    Takes up to the last 3 scenes and keeps the first 80 characters of each
    narrator_text.

    Args:
        scenes: List of Scene objects generated so far.

    Returns:
        A one-line summary string, or empty string if no scenes yet.
    """
    if not scenes:
        return ""
    recent = scenes[-3:]
    parts = [s.narrator_text[:80].rstrip().rstrip(".") + "…" for s in recent]
    return " | ".join(parts)


def _parse_scenes_from_json(
    content: str, offset: int = 0, max_scenes: int = 0
) -> list:
    """
    Parses a JSON string (possibly dirty) into a list of raw scene dicts.
    Returns an empty list if parsing fails.

    Args:
        content: Raw LLM output string.
        offset: Scene number to start from (for correct renumbering).
        max_scenes: If > 0, truncate the result to this many scenes.

    Returns:
        List of Scene objects.
    """
    cleaned = _clean_json(content)
    # Try to fix typographic quotes
    for src, dst in [("\u201c", '"'), ("\u201d", '"'),
                     ("\u2018", "'"), ("\u2019", "'")]:
        cleaned = cleaned.replace(src, dst)

    try:
        data = json.loads(cleaned)
    except json.JSONDecodeError:
        return []

    scenes_list = None
    for key in ("scenes", "escenas", "script", "guion", "video_scenes", "scene"):
        val = data.get(key) if isinstance(data, dict) else None
        if isinstance(val, list) and val:
            scenes_list = val
            break
    if scenes_list is None and isinstance(data, list):
        scenes_list = data
    if not scenes_list:
        return []

    result = []
    for i, raw in enumerate(scenes_list):
        if not isinstance(raw, dict):
            continue
        narrator_text = (
            raw.get("narrator_text") or raw.get("texto_narrador")
            or raw.get("narrator") or raw.get("narrador")
            or raw.get("text") or ""
        ).strip()
        video_query = (
            raw.get("video_query") or raw.get("query")
            or raw.get("visual") or raw.get("video") or ""
        ).strip()
        if not narrator_text:
            continue
        if not video_query:
            video_query = "nature landscape"
        video_query = " ".join(video_query.split()[:5])
        result.append(
            Scene(number=offset + len(result) + 1,
                  narrator_text=narrator_text,
                  video_query=video_query)
        )
    if max_scenes > 0:
        result = result[:max_scenes]
    return result


def _call_ollama(model: str, system_prompt: str, user_prompt: str,
                 context_size: int, num_predict: int) -> tuple[str, str]:
    """
    Makes a single ollama.chat call and returns (content, done_reason).

    Handles the thinking-model edge case where content is empty but the
    answer is embedded inside message.thinking.

    Returns:
        (content_str, done_reason_str)
    """
    try:
        response = ollama.chat(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            format="json",
            options={"num_ctx": context_size, "num_predict": num_predict},
        )
    except Exception as e:
        raise ConnectionError(
            f"Error connecting to Ollama. Is the server running?\n"
            f"Run: ollama serve\nDetails: {e}"
        )

    content = response["message"]["content"]

    # Thinking models may leave content empty if reasoning consumed all tokens.
    if not content.strip():
        thinking = response["message"].get("thinking", "") or ""
        if thinking:
            log.warning("  content is empty; scanning thinking field for JSON...")
            blocks = re.findall(r'\{[\s\S]*\}', thinking)
            if blocks:
                content = blocks[-1]
                log.info(f"  Found JSON in thinking field ({len(content)} chars).")

    done_reason = (
        response.get("done_reason", "") or response.get("stop_reason", "")
    )
    return content, done_reason


def generate_script(
    pdf_text: str,
    model: str = "qwen3",
    max_scenes: int = 8,
    custom_instructions: str = "",
    chunk_size: int = 4096,
    narration_language: str = "Spanish",
    on_progress=None,
) -> Script:
    """
    Converts PDF text into a narrated video script by calling a local LLM
    (via Ollama) one chunk at a time.

    Chunk-based strategy
    --------------------
    Instead of truncating the PDF to fit a single context window, the text is
    split into chunks whose size is controlled by *chunk_size* (in tokens).
    For each chunk the function derives the required Ollama ``num_ctx``
    automatically:

        num_ctx = next_power_of_two(
            chunk_size + output_budget + system_prompt + thinking_overhead
        )

    This means the user only needs to set how many tokens of PDF content they
    want per call; the context window is calculated for them.

    Thinking models (names containing "thinking", "think", "qwq", "r1",
    "reasoner") receive an extra 2048-token overhead in both ``num_predict``
    and the context window so the reasoning chain does not crowd out the JSON.

    Args:
        pdf_text: Text extracted from the PDF.
        model: Ollama model name.
        max_scenes: Total number of scenes to generate across all chunks.
        custom_instructions: Free-form instructions injected into the system
            prompt.  If empty, DEFAULT_CUSTOM_INSTRUCTIONS is used.
        chunk_size: Number of PDF-text tokens per LLM call.  The actual
            context window is derived from this value automatically.
            Default: 4096.
        narration_language: Language label forced into the system prompt (e.g.
            "Spanish", "English (American)").
        on_progress: Optional callable(chunk_idx: int, total_chunks: int)
            called before each chunk call so the GUI can update its progress
            bar.

    Returns:
        Script with all generated scenes renumbered from 1.

    Raises:
        ConnectionError: If Ollama is not reachable.
        ValueError: If no valid scenes could be extracted from any chunk.
    """
    thinking = _is_thinking_model(model)

    # ── Step 1: determine chunk size in characters and split ──────────────────
    # Conservative estimate: 1 token ≈ 3 characters.
    max_chars_per_chunk = max(500, chunk_size * _CHARS_PER_TOKEN)
    chunks = _split_into_chunks(pdf_text, max_chars_per_chunk)
    n_chunks = len(chunks)

    log.info(
        f"  PDF split into {n_chunks} chunk(s) "
        f"(chunk_size={chunk_size} tokens, "
        f"~{max_chars_per_chunk} chars/chunk)"
    )

    # ── Step 2: distribute scenes across chunks ───────────────────────────────
    # Rules:
    #   • Minimum total scenes = n_chunks (at least 1 per chunk).
    #   • Total scenes must be a multiple of n_chunks so every chunk gets
    #     exactly the same number of scenes (no remainder, no last-chunk spike).
    #   • If the user's max_scenes is below the minimum or is not a multiple,
    #     round UP to the next valid multiple and log a warning.
    min_scenes      = n_chunks                                # 1 scene / chunk
    # Round max_scenes up to the nearest multiple of n_chunks
    adjusted        = max(max_scenes, min_scenes)
    remainder_adj   = adjusted % n_chunks
    if remainder_adj != 0:
        adjusted += n_chunks - remainder_adj
    if adjusted != max_scenes:
        log.warning(
            f"  max_scenes adjusted from {max_scenes} → {adjusted} "
            f"(must be a non-zero multiple of {n_chunks} chunks; "
            f"valid values: {', '.join(str(n_chunks * k) for k in range(1, 6))}…)"
        )
    spc = adjusted // n_chunks              # scenes per chunk — identical for all
    scenes_per_chunk = [spc] * n_chunks

    # ── Step 3: derive num_ctx for the heaviest chunk ─────────────────────────
    context_size = _calculate_context_size(chunk_size, spc, thinking)
    num_predict  = spc * _TOKENS_PER_SCENE + _OUTPUT_BASE_TOKENS
    if thinking:
        num_predict += _THINKING_OVERHEAD

    log.info(
        f"  Scenes: {adjusted} total ({spc}/chunk × {n_chunks} chunks)  "
        f"| context_size (num_ctx) = {context_size} tokens  "
        f"[chunk={chunk_size} + output={num_predict} + "
        f"sys={_SYSTEM_PROMPT_TOKENS}"
        + (f" + thinking={_THINKING_OVERHEAD}" if thinking else "")
        + f", rounded to next power of 2]"
    )
    if thinking:
        log.info(f"  Thinking model detected ('{model}'). "
                 f"Adding {_THINKING_OVERHEAD} token overhead for reasoning.")

    # ── Step 4: process each chunk ────────────────────────────────────────────
    all_scenes: list[Scene] = []
    previous_summary = ""

    for chunk_idx, (chunk_text, spc) in enumerate(
            zip(chunks, scenes_per_chunk), start=1):

        if on_progress:
            on_progress(chunk_idx, n_chunks)

        log.info(
            f"  ── Chunk {chunk_idx}/{n_chunks}: "
            f"{len(chunk_text)} chars, {spc} scene(s) requested ──"
        )

        scenes = _generate_chunk_attempt(
            chunk_text=chunk_text,
            chunk_idx=chunk_idx,
            total_chunks=n_chunks,
            scenes_for_chunk=spc,
            previous_summary=previous_summary,
            model=model,
            context_size=context_size,
            num_predict=num_predict,
            custom_instructions=custom_instructions,
            narration_language=narration_language,
            scene_offset=len(all_scenes),
            attempt=1,
        )

        if scenes:
            all_scenes.extend(scenes)
            previous_summary = _summarize_scenes(all_scenes)
            log.info(f"  Chunk {chunk_idx}/{n_chunks}: {len(scenes)} scene(s) added "
                     f"(total so far: {len(all_scenes)})")
        else:
            log.warning(f"  Chunk {chunk_idx}/{n_chunks}: no valid scenes extracted, skipping.")

    if not all_scenes:
        raise ValueError("The LLM did not generate any valid scenes across all chunks.")

    # Renumber scenes 1..N
    for idx, scene in enumerate(all_scenes, start=1):
        scene.number = idx

    log.info(f"  Script complete: {len(all_scenes)} scenes across {n_chunks} chunk(s).")
    script = Script()
    script.scenes = all_scenes
    script.adjusted_max_scenes = adjusted
    script.n_chunks = n_chunks
    return script


def _generate_chunk_attempt(
    chunk_text: str,
    chunk_idx: int,
    total_chunks: int,
    scenes_for_chunk: int,
    previous_summary: str,
    model: str,
    context_size: int,
    num_predict: int,
    custom_instructions: str,
    narration_language: str,
    scene_offset: int,
    attempt: int,
) -> list:
    """
    Single attempt to generate scenes for one PDF chunk.

    Retries up to 3 times with progressively fewer scenes if the response is
    truncated or contains invalid JSON.

    Args:
        chunk_text: The PDF text for this chunk.
        chunk_idx: 1-based index of this chunk.
        total_chunks: Total number of chunks.
        scenes_for_chunk: How many scenes to request.
        previous_summary: Short summary of already-narrated scenes (may be "").
        model: Ollama model name.
        context_size: num_ctx to pass to Ollama.
        num_predict: num_predict to pass to Ollama.
        custom_instructions: Free-form instructions.
        narration_language: Language label for the system prompt.
        scene_offset: Number of scenes already generated (for numbering).
        attempt: Current attempt number (1-3).

    Returns:
        List of Scene objects (may be empty if all retries failed).
    """
    # Build a chunk-aware system prompt
    part_header = f"Part {chunk_idx} of {total_chunks} of the document."
    if chunk_idx == total_chunks and total_chunks > 1:
        part_header += " This is the FINAL part — write a conclusion scene."
    context_note = ""
    if previous_summary:
        context_note = (
            f"\nALREADY NARRATED (do NOT repeat these topics):\n{previous_summary}\n"
            f"Continue naturally from where the narration left off."
        )

    system_prompt = build_system_prompt(
        scenes_for_chunk, custom_instructions, narration_language,
        chunk_header=part_header + context_note,
    )
    user_prompt = (
        f"Convert the following text excerpt into a narrated video script "
        f"({scenes_for_chunk} scene(s) for this part):\n\n"
        f"---START OF EXCERPT---\n{chunk_text}\n---END OF EXCERPT---"
    )

    log.info(
        f"    context_size={context_size}, num_predict={num_predict}, "
        f"scenes={scenes_for_chunk}, attempt={attempt}/3"
    )

    content, done_reason = _call_ollama(
        model, system_prompt, user_prompt, context_size, num_predict,
    )
    log.info(f"    LLM response: {len(content)} chars, done_reason={done_reason!r}")

    # If truncated and retries remain, reduce scenes and double num_predict
    if done_reason == "length" and attempt < 3:
        reduced = max(1, scenes_for_chunk // 2) if attempt == 1 else 1
        log.warning(
            f"    Truncated (done_reason=length). "
            f"Retrying chunk {chunk_idx} with {reduced} scene(s) "
            f"and num_predict={num_predict * 2} "
            f"(attempt {attempt + 1}/3)..."
        )
        return _generate_chunk_attempt(
            chunk_text, chunk_idx, total_chunks, reduced, previous_summary,
            model, context_size, num_predict * 2, custom_instructions,
            narration_language, scene_offset, attempt + 1,
        )

    scenes = _parse_scenes_from_json(
        content, offset=scene_offset, max_scenes=scenes_for_chunk
    )

    # If JSON was invalid and retries remain, reduce scenes and try again
    if not scenes and attempt < 3:
        reduced = max(1, scenes_for_chunk // 2) if attempt == 1 else 1
        log.warning(
            f"    No valid scenes from JSON. "
            f"Retrying chunk {chunk_idx} with {reduced} scene(s) "
            f"(attempt {attempt + 1}/3)..."
        )
        return _generate_chunk_attempt(
            chunk_text, chunk_idx, total_chunks, reduced, previous_summary,
            model, context_size, num_predict, custom_instructions,
            narration_language, scene_offset, attempt + 1,
        )

    return scenes


# ---------------------------------------------------------------------------
# 3. AUDIO MODULE (Kokoro 1.0 via kokoro-onnx)
# ---------------------------------------------------------------------------
class AudioEngine:
    """
    Generates TTS audio using Kokoro 1.0 with ONNX Runtime.

    Supports all Kokoro languages.  For espeak-backed languages (American
    English, British English, Spanish, French, Hindi, Italian, Portuguese)
    it uses ``misaki.espeak.EspeakG2P`` for phonemization.  For Japanese
    and Mandarin Chinese it falls back to Kokoro's built-in G2P.
    """

    def __init__(
        self,
        voice: str = "af_heart",
        speed: float = 1.0,
        lang_code: str = "",
    ):
        """
        Initializes the audio engine.

        Args:
            voice: Kokoro voice ID (e.g. ``af_heart``, ``em_alex``).
            speed: Speech speed (1.0 = normal).
            lang_code: Kokoro single-char language code (``a``, ``e``, …).
                       If empty, inferred from the voice prefix.
        """
        self.voice = voice
        self.speed = speed
        self.lang_code = lang_code or get_lang_code_for_voice(voice)
        self.kokoro = None
        self.g2p = None

    def _initialize(self):
        """Loads the Kokoro model and the appropriate G2P module (lazy)."""
        if self.kokoro is not None:
            return

        # Verify model files exist
        if not KOKORO_ONNX_PATH.exists():
            raise FileNotFoundError(
                f"Kokoro model not found at: {KOKORO_ONNX_PATH}\n"
                f"Download it from: https://github.com/thewh1teagle/kokoro-onnx/releases"
            )
        if not KOKORO_VOICES_PATH.exists():
            raise FileNotFoundError(
                f"Kokoro voices not found at: {KOKORO_VOICES_PATH}\n"
                f"Download them from: https://github.com/thewh1teagle/kokoro-onnx/releases"
            )

        log.info("  Loading Kokoro v1.0 model (this may take a few seconds)...")
        self.kokoro = Kokoro(str(KOKORO_ONNX_PATH), str(KOKORO_VOICES_PATH))

        # Initialize G2P based on language
        lang_info = KOKORO_LANGUAGES.get(self.lang_code, {})
        espeak_code = lang_info.get("espeak_code")
        lang_label = lang_info.get("label", self.lang_code)

        if espeak_code is not None:
            # espeak-backed language — use misaki EspeakG2P
            try:
                from misaki.espeak import EspeakG2P
                self.g2p = EspeakG2P(language=espeak_code)
                log.info(f"  G2P initialized for {lang_label} (espeak: {espeak_code})")
            except ImportError:
                log.warning(
                    f"  misaki not available. Using direct mode for {lang_label}.\n"
                    f"  For better quality: pip install misaki"
                )
                self.g2p = None
        else:
            # Japanese / Chinese — Kokoro handles G2P internally
            log.info(f"  {lang_label}: using Kokoro built-in G2P (no espeak needed)")
            self.g2p = None

    @staticmethod
    def _clean_tts_text(text: str) -> str:
        """
        Removes characters that TTS engines read aloud literally:
          - Emoji (Unicode ranges for emoticons, symbols, pictographs, etc.)
          - Asterisks used as markdown emphasis markers  (* and **)
          - Isolated hash characters used as markdown headings (# at line start)
          - Leading/trailing whitespace after cleaning.
        """
        # Strip markdown emphasis: **bold**, *italic*, ***both***
        text = re.sub(r'\*+', '', text)
        # Strip markdown headings: ## Title → Title
        text = re.sub(r'^\s*#+\s*', '', text, flags=re.MULTILINE)
        # Strip emoji — covers the main Unicode emoji blocks:
        #   U+1F600-1F64F  Emoticons
        #   U+1F300-1F5FF  Misc symbols & pictographs
        #   U+1F680-1F6FF  Transport & map
        #   U+1F700-1F77F  Alchemical symbols
        #   U+1F780-1F7FF  Geometric shapes extended
        #   U+1F800-1F8FF  Supplemental arrows-C
        #   U+1F900-1F9FF  Supplemental symbols & pictographs
        #   U+1FA00-1FA6F  Chess / symbols
        #   U+1FA70-1FAFF  Symbols & pictographs extended-A
        #   U+2600-26FF    Misc symbols (☀ ☁ ♥ etc.)
        #   U+2700-27BF    Dingbats
        #   U+FE00-FE0F    Variation selectors (emoji modifiers)
        #   U+1F1E0-1F1FF  Regional indicator letters (flag emoji)
        text = re.sub(
            r'[\U0001F600-\U0001F64F'
            r'\U0001F300-\U0001F5FF'
            r'\U0001F680-\U0001F6FF'
            r'\U0001F700-\U0001F77F'
            r'\U0001F780-\U0001F7FF'
            r'\U0001F800-\U0001F8FF'
            r'\U0001F900-\U0001F9FF'
            r'\U0001FA00-\U0001FA6F'
            r'\U0001FA70-\U0001FAFF'
            r'\U00002600-\U000026FF'
            r'\U00002700-\U000027BF'
            r'\U0000FE00-\U0000FE0F'
            r'\U0001F1E0-\U0001F1FF'
            r']',
            '',
            text,
        )
        # Collapse multiple spaces left by removals
        text = re.sub(r'  +', ' ', text)
        return text.strip()

    def generate_audio(self, text: str, output_path: str) -> float:
        """
        Generates a .wav file from text in the configured language.

        Args:
            text: Text to synthesize (in the voice's language).
            output_path: Path where the .wav file will be saved.

        Returns:
            Exact audio duration in seconds.
        """
        self._initialize()
        text = self._clean_tts_text(text)

        try:
            if self.g2p is not None:
                # Convert text to phonemes via misaki espeak
                # misaki 0.7+ EspeakG2P returns str directly
                phonemes = self.g2p(text)
                if not phonemes:
                    log.warning("  G2P returned empty phonemes, using text directly.")
                    phonemes = text
                samples, sample_rate = self.kokoro.create(
                    phonemes,
                    voice=self.voice,
                    speed=self.speed,
                    is_phonemes=True,
                )
            else:
                # Direct mode: Japanese, Chinese, or fallback when misaki
                # is not installed. Pass lang_code so Kokoro picks the
                # correct internal G2P.
                samples, sample_rate = self.kokoro.create(
                    text,
                    voice=self.voice,
                    speed=self.speed,
                    lang=self.lang_code,
                )

            # Save audio
            sf.write(output_path, samples, sample_rate)

            # Calculate exact duration from samples
            duration = len(samples) / sample_rate
            log.info(
                f"  Audio generated: {duration:.2f}s "
                f"({len(samples)} samples @ {sample_rate}Hz)"
            )
            return duration

        except Exception as e:
            raise RuntimeError(f"Error generating audio with Kokoro: {e}")


# ---------------------------------------------------------------------------
# 4. VISUAL MODULE (Pexels API - 100% Free)
# ---------------------------------------------------------------------------
PEXELS_API_URL = "https://api.pexels.com/videos/search"


def get_pexels_api_key() -> str:
    """
    Retrieves the Pexels API key from environment variable.

    Returns:
        The API key.

    Raises:
        EnvironmentError: If the variable is not set.
    """
    api_key = os.environ.get("PEXELS_API_KEY", "")
    if not api_key:
        raise EnvironmentError(
            "PEXELS_API_KEY environment variable is not set.\n"
            "Get a free key at: https://www.pexels.com/api/\n"
            "Set it with: export PEXELS_API_KEY='your_key_here'"
        )
    return api_key


def search_pexels_video(
    query: str,
    api_key: str,
    orientation: str = "landscape",
    target_duration: float = 0.0,
) -> dict | None:
    """
    Searches for a video on Pexels and returns info about the best result.

    Fetches up to 15 candidates and selects the one whose duration is closest
    to *target_duration* (the audio length). This avoids always picking the
    first (most popular) result, which is often only loosely related to the
    query despite having a matching tag.

    Args:
        query: Search terms in English (2-5 words).
        api_key: Pexels API key.
        orientation: "landscape", "portrait" or "square".
        target_duration: Preferred video duration in seconds (0 = pick longest).

    Returns:
        Dict with 'url' (download link), 'width', 'height', 'duration' or None.
    """
    headers = {"Authorization": api_key}
    params = {
        "query": query,
        "per_page": 15,
        "orientation": orientation,
        "size": "medium",
    }

    try:
        resp = requests.get(PEXELS_API_URL, headers=headers, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json()
    except requests.exceptions.RequestException as e:
        log.error(f"  Pexels API error: {e}")
        return None

    videos = data.get("videos", [])
    if not videos:
        log.warning(f"  No videos found for '{query}'")
        return None

    # Collect all valid candidates (video + best file) from the full result set
    candidates = []
    for video in videos:
        files = video.get("video_files", [])
        best_file = None

        # Prefer the smallest resolution that is still >= 720p HD
        for f in files:
            if f.get("file_type") != "video/mp4":
                continue
            w = f.get("width", 0)
            h = f.get("height", 0)
            if w >= 1280 and h >= 720:
                if best_file is None or w < best_file.get("width", 9999):
                    best_file = f

        # Fallback: any mp4 if no HD found
        if best_file is None:
            for f in files:
                if f.get("file_type") == "video/mp4":
                    best_file = f
                    break

        if best_file:
            candidates.append({
                "url": best_file["link"],
                "width": best_file.get("width", 0),
                "height": best_file.get("height", 0),
                "duration": video.get("duration", 0),
            })

    if not candidates:
        log.warning(f"  No mp4 files found for '{query}'")
        return None

    # Select the candidate whose duration is closest to the target audio length.
    # If target_duration is 0 (unknown), pick the longest video (more material
    # for looping and less likely to loop with a visible cut).
    if target_duration > 0:
        best = min(candidates, key=lambda c: abs(c["duration"] - target_duration))
    else:
        best = max(candidates, key=lambda c: c["duration"])

    log.info(
        f"  Pexels: {len(candidates)} candidates for '{query}' → "
        f"selected {best['duration']}s video "
        f"(target {target_duration:.1f}s)"
    )
    return best


def download_video(url: str, output_path: str) -> bool:
    """
    Downloads a video from a URL.

    Args:
        url: Direct URL of the video file.
        output_path: Local path where the file will be saved.

    Returns:
        True if the download was successful.
    """
    try:
        log.info(f"  Downloading video...")
        resp = requests.get(url, stream=True, timeout=60)
        resp.raise_for_status()

        total_size = int(resp.headers.get("content-length", 0))
        downloaded = 0

        with open(output_path, "wb") as f:
            for chunk in resp.iter_content(chunk_size=1024 * 1024):  # 1MB chunks
                f.write(chunk)
                downloaded += len(chunk)

        size_mb = downloaded / (1024 * 1024)
        log.info(f"  Downloaded: {size_mb:.1f} MB → {output_path}")
        return True

    except requests.exceptions.RequestException as e:
        log.error(f"  Error downloading video: {e}")
        return False


def search_and_download_video(
    query: str,
    api_key: str,
    output_path: str,
    orientation: str = "landscape",
    target_duration: float = 0.0,
) -> bool:
    """
    Searches and downloads a video from Pexels.

    Fallback strategy (in order):
      1. Full query (e.g. "scientists analyzing dna samples")
      2. First two words of the query (e.g. "scientists analyzing")
      3. First word of the query (e.g. "scientists")
      4. Generic domain-neutral fallbacks: "people working", "abstract motion",
         "urban timelapse"

    Args:
        query: Original search terms (2-5 words from the LLM).
        api_key: Pexels API key.
        output_path: Path where the video will be saved.
        orientation: "landscape", "portrait" or "square".
        target_duration: Audio duration in seconds — used to pick the best
            Pexels result (closest duration = less looping).

    Returns:
        True if downloaded successfully.
    """
    words = query.split()

    # Build the fallback chain: progressively shorter versions of the original
    # query, then generic fallbacks as last resort.
    attempts: list[str] = [query]
    if len(words) > 2:
        attempts.append(" ".join(words[:2]))   # first two words
    if len(words) > 1:
        attempts.append(words[0])              # first word only
    attempts += ["people working", "abstract motion", "urban timelapse"]

    # Remove duplicates while preserving order
    seen: set[str] = set()
    unique_attempts: list[str] = []
    for a in attempts:
        if a not in seen:
            seen.add(a)
            unique_attempts.append(a)

    info = None
    for attempt in unique_attempts:
        log.info(f"  Searching Pexels: '{attempt}'")
        info = search_pexels_video(attempt, api_key, orientation, target_duration)
        if info is not None:
            if attempt != query:
                log.warning(f"  Original query '{query}' failed — using fallback '{attempt}'")
            break

    if info is None:
        log.error(f"  Could not find any video (query: '{query}')")
        return False

    return download_video(info["url"], output_path)


# ---------------------------------------------------------------------------
# 5. ASSEMBLY MODULE (MoviePy)
# ---------------------------------------------------------------------------
def assemble_scene_from_raw(
    raw_video_path: str,
    audio_path: str,
    target_duration: float,
    output_path: str,
) -> str:
    """
    Trims/loops the raw stock video to the exact audio duration, resizes it,
    and mixes in the audio — all in a **single encode pass**.

    This replaces the previous two-step approach (fit_video_to_duration →
    assemble_scene) which wrote an intermediate _processed.mp4 and then
    re-encoded it a second time.  Doing it in one pass halves the CPU time
    per scene.

    Args:
        raw_video_path: Path to the video downloaded from Pexels.
        audio_path: Path to the .wav audio file for this scene.
        target_duration: Exact audio duration in seconds.
        output_path: Path for the finished scene video file (video + audio).

    Returns:
        Path to the assembled scene video (same as output_path).
    """
    clip = VideoFileClip(raw_video_path)
    audio = AudioFileClip(audio_path)

    log.info(
        f"  Original video: {clip.duration:.2f}s → Target: {target_duration:.2f}s"
    )

    # Trim or loop to match audio duration exactly
    if clip.duration >= target_duration:
        adjusted = clip.subclipped(0, target_duration)
    else:
        repetitions = int(target_duration / clip.duration) + 1
        adjusted = concatenate_videoclips([clip] * repetitions, method="compose")
        adjusted = adjusted.subclipped(0, target_duration)

    # Resize to target resolution if needed
    w, h = adjusted.size
    if w != TARGET_WIDTH or h != TARGET_HEIGHT:
        adjusted = adjusted.resized(new_size=(TARGET_WIDTH, TARGET_HEIGHT))

    # Set FPS and attach audio — single encode pass
    adjusted = adjusted.with_fps(TARGET_FPS).with_audio(audio)

    adjusted.write_videofile(
        output_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )

    clip.close()
    audio.close()
    adjusted.close()

    log.info(f"  Scene assembled: {output_path}")
    return output_path


def fit_video_to_duration(video_path: str, target_duration: float, output_path: str) -> str:
    """
    Adjusts a stock video to match the exact audio duration.

    .. deprecated::
        Use :func:`assemble_scene_from_raw` instead, which combines this step
        with audio mixing into a single encode pass.

    If the video is longer → trim it (subclip).
    If the video is shorter → loop it until it covers the duration.

    Also resizes to TARGET_WIDTH x TARGET_HEIGHT if needed.

    Args:
        video_path: Path to the video downloaded from Pexels.
        target_duration: Exact duration in seconds (from audio).
        output_path: Path where the processed video will be saved.

    Returns:
        Path to the processed video.
    """
    clip = VideoFileClip(video_path)
    video_duration = clip.duration

    log.info(
        f"  Original video: {video_duration:.2f}s → "
        f"Target: {target_duration:.2f}s"
    )

    if video_duration >= target_duration:
        # Video is longer: trim it
        adjusted = clip.subclipped(0, target_duration)
    else:
        # Video is shorter: loop it
        repetitions = int(target_duration / video_duration) + 1
        adjusted = concatenate_videoclips([clip] * repetitions, method="compose")
        adjusted = adjusted.subclipped(0, target_duration)

    # Resize to target resolution if needed
    w, h = adjusted.size
    if w != TARGET_WIDTH or h != TARGET_HEIGHT:
        adjusted = adjusted.resized(new_size=(TARGET_WIDTH, TARGET_HEIGHT))

    # Set target FPS
    adjusted = adjusted.with_fps(TARGET_FPS)

    adjusted.write_videofile(
        output_path,
        codec="libx264",
        audio=False,  # Audio is added later
        preset=TARGET_PRESET,
        logger=None,  # Suppress ffmpeg output
    )

    clip.close()
    adjusted.close()

    log.info(f"  Adjusted video saved: {output_path}")
    return output_path


def assemble_scene(scene: Scene, output_path: str) -> str:
    """
    Combines the processed video with the audio for a scene.

    Args:
        scene: Scene with audio and processed video paths.
        output_path: Path for the final scene video file.

    Returns:
        Path to the assembled video.
    """
    video = VideoFileClip(scene.processed_video_path)
    audio = AudioFileClip(scene.audio_path)

    video_with_audio = video.with_audio(audio)

    video_with_audio.write_videofile(
        output_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )

    video.close()
    audio.close()
    video_with_audio.close()

    log.info(f"  Scene assembled: {output_path}")
    return output_path


def concatenate_scenes(scene_paths: list[str], final_path: str) -> str:
    """
    Concatenates all scene files into a single final video **without
    re-encoding** using the ffmpeg ``concat`` demuxer.

    All scene files must share the same codec, resolution and frame-rate —
    which is guaranteed by :func:`assemble_scene_from_raw` (libx264 + aac,
    TARGET_WIDTH × TARGET_HEIGHT, TARGET_FPS).  Under these conditions ffmpeg
    simply copies the compressed packets straight into the output container in
    a fraction of the time that a full transcode would take.

    Falls back to the MoviePy re-encode path if ffmpeg is not available or
    the stream-copy fails for any reason.

    Args:
        scene_paths: Ordered list of paths to each assembled scene .mp4 file.
        final_path: Output path for the final concatenated video.

    Returns:
        Path to the final video (same as *final_path*).
    """
    import shutil
    import subprocess

    # ── Build a temporary concat list file ───────────────────────────────────
    # ffmpeg concat demuxer format:
    #   file '/absolute/path/to/scene.mp4'
    #   file '/absolute/path/to/scene2.mp4'
    #   ...
    list_fd, list_path = tempfile.mkstemp(suffix=".txt", prefix="freevi_concat_")
    try:
        with os.fdopen(list_fd, "w", encoding="utf-8") as f:
            for p in scene_paths:
                # Use absolute paths and escape single quotes
                abs_p = os.path.abspath(p).replace("'", "'\\''")
                f.write(f"file '{abs_p}'\n")

        cmd = [
            "ffmpeg", "-y",
            "-f", "concat",
            "-safe", "0",
            "-i", list_path,
            "-c", "copy",          # stream copy — no re-encode
            final_path,
        ]
        log.info(f"  ffmpeg concat (stream copy): {len(scene_paths)} scenes → {final_path}")
        result = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        if result.returncode != 0:
            err = result.stderr.decode(errors="replace")
            raise RuntimeError(f"ffmpeg concat failed:\n{err}")

    except FileNotFoundError:
        # ffmpeg binary not on PATH — fall back to MoviePy
        log.warning("  ffmpeg not found on PATH; falling back to MoviePy re-encode.")
        os.unlink(list_path)
        return _concatenate_scenes_moviepy(scene_paths, final_path)
    except Exception as e:
        log.warning(f"  ffmpeg concat failed ({e}); falling back to MoviePy re-encode.")
        return _concatenate_scenes_moviepy(scene_paths, final_path)
    finally:
        if os.path.exists(list_path):
            os.unlink(list_path)

    log.info(f"Final video generated: {final_path}")
    return final_path


def _concatenate_scenes_moviepy(scene_paths: list[str], final_path: str) -> str:
    """
    Fallback concatenation via MoviePy (full re-encode).
    Used only when the ffmpeg stream-copy path is unavailable.
    """
    clips = [VideoFileClip(path) for path in scene_paths]
    final_video = concatenate_videoclips(clips, method="compose")
    final_video.write_videofile(
        final_path,
        codec="libx264",
        audio_codec="aac",
        preset=TARGET_PRESET,
        logger=None,
    )
    for clip in clips:
        clip.close()
    final_video.close()
    log.info(f"Final video generated (MoviePy fallback): {final_path}")
    return final_path


# ---------------------------------------------------------------------------
# 6. MAIN ORCHESTRATOR
# ---------------------------------------------------------------------------
class VideoGenerator:
    """
    Orchestrates the entire video generation pipeline.

    Per-scene pipeline (strict order for synchronization):
      1. LLM generates narrator text + visual query
      2. Kokoro generates audio → exact duration is measured
      3. Pexels downloads video → trimmed/looped to that duration
      4. MoviePy combines audio + video
      5. All scenes are concatenated at the end
    """

    def __init__(
        self,
        pdf_path: str,
        llm_model: str = "qwen3",
        voice: str = "af_heart",
        voice_speed: float = 1.0,
        output_path: str = "output/video_final.mp4",
        max_scenes: int = 8,
        chunk_size: int = 4096,
        lang_code: str = "a",
    ):
        self.pdf_path = pdf_path
        self.llm_model = llm_model
        self.output_path = output_path
        self.max_scenes = max_scenes
        self.chunk_size = chunk_size
        self.lang_code = lang_code
        self.audio_engine = AudioEngine(
            voice=voice, speed=voice_speed, lang_code=lang_code,
        )
        self.pexels_api_key = get_pexels_api_key()
        self.temp_dir = tempfile.mkdtemp(prefix="freevi_")
        log.info(f"Temporary directory: {self.temp_dir}")

    def run(self):
        """Runs the full pipeline."""
        # ── Step 1: Extract PDF text ──
        log.info("=" * 60)
        log.info("STEP 1/5: Extracting text from PDF...")
        log.info("=" * 60)
        pdf_text = extract_pdf_text(self.pdf_path)

        # ── Step 2: Generate script with LLM ──
        log.info("=" * 60)
        log.info(f"STEP 2/5: Generating script with {self.llm_model}...")
        log.info("=" * 60)
        narration_lang = get_language_label(self.lang_code)
        script = generate_script(
            pdf_text,
            self.llm_model,
            max_scenes=self.max_scenes,
            chunk_size=self.chunk_size,
            narration_language=narration_lang,
        )

        # Show script summary
        for scene in script.scenes:
            log.info(
                f"  Scene {scene.number}: "
                f"[{scene.video_query}] "
                f"{scene.narrator_text[:60]}..."
            )

        # ── Steps 3–4: Process each scene ──
        final_scene_paths = []

        for scene in script.scenes:
            log.info("=" * 60)
            log.info(f"SCENE {scene.number}/{len(script.scenes)}")
            log.info("=" * 60)

            # ── 3a: Generate audio and measure exact duration ──
            log.info(f"  [Audio] Generating narration...")
            audio_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_audio.wav"
            )
            duration = self.audio_engine.generate_audio(scene.narrator_text, audio_path)
            scene.audio_path = audio_path
            scene.audio_duration = duration
            log.info(f"  [Audio] Exact duration: {duration:.3f} seconds")

            # ── 3b: Download stock video ──
            log.info(f"  [Video] Searching '{scene.video_query}' on Pexels...")
            raw_video_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_raw.mp4"
            )
            success = search_and_download_video(
                scene.video_query,
                self.pexels_api_key,
                raw_video_path,
                target_duration=duration,
            )

            if not success:
                log.error(
                    f"  Could not get video for scene {scene.number}. "
                    f"Generating black fallback video."
                )
                raw_video_path = self._generate_black_video(duration, raw_video_path)

            scene.video_path = raw_video_path

            # ── 3c: Fit video + mix audio in a single encode pass ──
            log.info(f"  [Assembly] Encoding video + audio in one pass...")
            scene_final_path = os.path.join(
                self.temp_dir, f"scene_{scene.number:02d}_final.mp4"
            )
            assemble_scene_from_raw(
                raw_video_path, audio_path, duration, scene_final_path
            )
            final_scene_paths.append(scene_final_path)

            log.info(f"  Scene {scene.number} complete.")

        # ── Step 5: Concatenate all scenes ──
        log.info("=" * 60)
        log.info("STEP 5/5: Concatenating all scenes...")
        log.info("=" * 60)

        # Ensure output directory exists
        output_dir = os.path.dirname(self.output_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)

        if len(final_scene_paths) == 1:
            # Only one scene: copy directly
            import shutil
            shutil.copy2(final_scene_paths[0], self.output_path)
        else:
            concatenate_scenes(final_scene_paths, self.output_path)

        log.info("=" * 60)
        log.info(f"FINAL VIDEO: {self.output_path}")
        log.info(f"Temporary files in: {self.temp_dir}")
        log.info("=" * 60)

        return self.output_path

    def _generate_black_video(self, duration: float, output_path: str) -> str:
        """Generates a black video as fallback when Pexels fails."""
        clip = ColorClip(
            size=(TARGET_WIDTH, TARGET_HEIGHT),
            color=(0, 0, 0),
            duration=duration,
        )
        clip = clip.with_fps(TARGET_FPS)
        clip.write_videofile(
            output_path,
            codec="libx264",
            audio=False,
            preset=TARGET_PRESET,
            logger=None,
        )
        clip.close()
        return output_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="FreeVi - Automatically generate videos from a PDF",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python freevi.py document.pdf
  python freevi.py book.pdf --model qwen3 --voice af_heart --lang a --output result.mp4

Available languages (--lang):
  a = English (American)    b = English (British)
  e = Spanish               f = French
  h = Hindi                 i = Italian
  j = Japanese              p = Portuguese (Brazilian)
  z = Chinese (Mandarin)

Prerequisites:
  1. Ollama running: ollama serve
  2. Model downloaded: ollama pull qwen3
  3. Kokoro models in ./kokoro-v1.0/
  4. Environment variable: export PEXELS_API_KEY='your_key'
        """,
    )

    parser.add_argument(
        "pdf",
        help="Path to the input PDF file",
    )
    parser.add_argument(
        "--model",
        default="qwen3",
        help="Ollama model to use (default: qwen3)",
    )
    parser.add_argument(
        "--voice",
        default="af_heart",
        help="Kokoro voice ID (default: af_heart). Must match --lang.",
    )
    parser.add_argument(
        "--lang",
        default="a",
        choices=list(KOKORO_LANGUAGES.keys()),
        help="Narration language code (default: a = English American). "
             "Choices: " + ", ".join(
                 f"{k}={v['label']}" for k, v in KOKORO_LANGUAGES.items()
             ),
    )
    parser.add_argument(
        "--speed",
        type=float,
        default=1.0,
        help="Narration speed, 1.0 = normal (default: 1.0)",
    )
    parser.add_argument(
        "--output",
        default="output/video_final.mp4",
        help="Output video path (default: output/video_final.mp4)",
    )
    parser.add_argument(
        "--max-scenes",
        type=int,
        default=8,
        help="Maximum number of scenes to generate (default: 8)",
    )
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=4096,
        help="PDF chunk size in tokens per LLM call (default: 4096). "
             "The context window is derived automatically from this value.",
    )

    args = parser.parse_args()

    log.info("=" * 60)
    log.info("  FreeVi - Video Generator from PDF")
    log.info("=" * 60)
    log.info(f"  PDF:          {args.pdf}")
    log.info(f"  Model:        {args.model}")
    log.info(f"  Language:     {args.lang} ({get_language_label(args.lang)})")
    log.info(f"  Voice:        {args.voice}")
    log.info(f"  Speed:        {args.speed}")
    log.info(f"  Max scenes:   {args.max_scenes}")
    log.info(f"  Chunk size:   {args.chunk_size} tokens")
    log.info(f"  Output:       {args.output}")
    log.info("=" * 60)

    try:
        generator = VideoGenerator(
            pdf_path=args.pdf,
            llm_model=args.model,
            voice=args.voice,
            voice_speed=args.speed,
            output_path=args.output,
            max_scenes=args.max_scenes,
            chunk_size=args.chunk_size,
            lang_code=args.lang,
        )
        final_path = generator.run()
        log.info(f"\nVideo generated successfully: {final_path}")

    except FileNotFoundError as e:
        log.error(f"\nFile not found: {e}")
        sys.exit(1)
    except ConnectionError as e:
        log.error(f"\nConnection error: {e}")
        sys.exit(1)
    except EnvironmentError as e:
        log.error(f"\nConfiguration error: {e}")
        sys.exit(1)
    except ValueError as e:
        log.error(f"\nData error: {e}")
        sys.exit(1)
    except KeyboardInterrupt:
        log.info("\nProcess interrupted by user.")
        sys.exit(130)
    except Exception as e:
        log.error(f"\nUnexpected error: {e}", exc_info=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
